### PR TITLE
CI: Add DPMI (DOS) memory leak checks

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
`libi86-testsuite-ia16-elf not installed - skipping those`
Can I "fix" that on fedora?

**Comment by andrewbird** [comment]
> libi86-testsuite-ia16-elf

To be honest I don't even know if gcc-ia16 is packaged for fedora, if it is then the libi86 testsuite is probably in the same place. In any case this message is not fatal to dosemu's testing and the libi86 testsuite itself is not required for this specific test.

**Comment by andrewbird** [comment]
It's also possible you have it installed and I'm assuming it's present in the wrong place. I currently try executing it as
```/usr/ia16-elf/libexec/libi86/tests/testsuite --list```. Have a look around whereever libi86 is installed.

**Comment by stsp** [comment]
```
/home/stas/src/dosemu2-devel/test/func_libi86_testsuite.py:22: SyntaxWarning: invalid escape sequence '\s'
```

**Comment by stsp** [comment]
So I run both "narmal" and "nofree"
tests, and it says OK.

**Comment by andrewbird** [comment]
> So I run both "narmal" and "nofree"
tests, and it says OK.

Yes that's exactly what I see here locally, but on CI it always fails. Not sure how to trigger that here, perhaps more iterations, or a different allocation size are required.

> SyntaxWarning: invalid escape sequence

I'll fix that, it seems I missed one of the new python 3.12 warnings.

**Comment by stsp** [comment]
```
C:\>c:\dpmileak TEST0 nofree
INFO: (TEST0) DPMI allocation (DOS) info: SEGMENT=04c2, SELECTOR=01bf
INFO: (TEST0) Skipping Free (DOS)
DONE: (TEST0)

C:\>c:\dpmileak TEST1 nofree
INFO: (TEST1) DPMI allocation (DOS) info: SEGMENT=04c3, SELECTOR=01bf
INFO: (TEST1) Skipping Free (DOS)
DONE: (TEST1)

C:\>c:\dpmileak TEST2 nofree
INFO: (TEST2) DPMI allocation (DOS) info: SEGMENT=04c3, SELECTOR=01bf
INFO: (TEST2) Skipping Free (DOS)
DONE: (TEST2)

C:\>c:\dpmileak TEST3 nofree
INFO: (TEST3) DPMI allocation (DOS) info: SEGMENT=04c3, SELECTOR=01bf
INFO: (TEST3) Skipping Free (DOS)
DONE: (TEST3)
```

So on CI we see 4c2 only once, and
then, reliably, 4c3.
Would it be possible to dump mcbs
with dosdebug, to see if the MCB map
was actually altered, and what happens
on 4c2?

**Comment by stsp** [comment]
It also seems to happen on a "normal"
test. So if there is a leak somewhere, its
in fdpp... Which is not good. :)

**Comment by andrewbird** [comment]
It makes sense to be in FDPP, as the same test doesn't fail under MS-DOS 6.22.

I'm not sure how I can invoke dosdebug at the right time or actually initiate the mcbs command in the CI.

**Comment by stsp** [comment]
I added the patch to devel, which
allows you to do:
`echo mcbs | dosdebug`

**Comment by andrewbird** [comment]
Here's a run with `echo mcbs | dosdebug` interleaved
https://github.com/dosemu2/dosemu2/actions/runs/8308440277/job/22738672373?pr=2176

**Comment by stsp** [comment]
Yes, interesting.
Looks like the mcb fragmentation
makes it to choose the different
load address...

**Comment by stsp** [comment]
Where does it writes the logs when
test succeeds? I'd like to see the local
mcb map.

**Comment by andrewbird** [comment]
Salient portion looks like
~~~
C:\>unix /home/runner/work/dosemu2/dosemu2/do_mcbs.sh^M                         
dosdebug> mcbs                                                                  
dosdebug>                                                                       
dosdebug> ^M          ^M                                                        
DOSEMU Debugger V0.6 connected                                                  
- type ? to get help on commands -                                              
system state: emulated,running in real mode while in DPMI                       
AX=ae00  BX=0000  CX=ff2d  DX=ffff  SI=0102  DI=0000  SP=01fa  BP=0000          
DS=a01d  ES=0000  FS=0000  GS=0000  FL=000b3284                                 
CS:IP=ff10:0131       SS:SP=adb1:01fa                                           
                                                                                
ff10:0131 F4               hlt                                                  
009c:0000 0x9f62 [FREE] (END)                                                   
<snip>
 C:\>c:\dpmileak TEST0 normal^M                                                  
INFO: (TEST0) DPMI allocation (DOS) info: SEGMENT=04c2, SELECTOR=01bf           
INFO: (TEST0) Successful Free (DOS)                                             
DONE: (TEST0)^M                                                                 
C:\>unix /home/runner/work/dosemu2/dosemu2/do_mcbs.sh^M                         
dosdebug> mcbs                                                                  
dosdebug>                                                                       
dosdebug> ^M          ^M                                                        
DOSEMU Debugger V0.6 connected                                                  
- type ? to get help on commands -                                              
system state: emulated,running in real mode while in DPMI                       
AX=2122  BX=0004  CX=0000  DX=0a9c  SI=faab  DI=0a88  SP=0a72  BP=0a8e          
DS=fa10  ES=a00c  FS=0000  GS=0000  FL=000b3244                                 
CS:IP=ff10:012a       SS:SP=fa96:0a72                                           
                                                                                
ff10:012a F4               hlt                                                  
                                                                                
ADDR(LOW) PARAS  OWNER                                                          
009c:0000 0x0013 [FREE]                                                         
00b0:0000 0x0410 [FREE]                                                         
04c1:0000 0x1000 [FREE]                                                         
14c2:0000 0x8b3c [FREE] (END)                                                   
<snip>
C:\>c:\dpmileak TEST1 normal^M                                                  
INFO: (TEST1) DPMI allocation (DOS) info: SEGMENT=04c3, SELECTOR=01bf           
INFO: (TEST1) Successful Free (DOS)                                             
DONE: (TEST1)^M                                                                 
C:\>unix /home/runner/work/dosemu2/dosemu2/do_mcbs.sh^M                         
dosdebug> mcbs                                                                  
dosdebug>                                                                       
dosdebug> ^M          ^M                                                        
DOSEMU Debugger V0.6 connected                                                  
- type ? to get help on commands -                                              
system state: emulated,running in real mode while in DPMI                       
AX=2122  BX=0004  CX=0000  DX=0a9c  SI=faab  DI=0a88  SP=0a72  BP=0a8e          
DS=fa10  ES=a00c  FS=0000  GS=0000  FL=000b3244                                 
CS:IP=ff10:012a       SS:SP=fa96:0a72                                           
                                                                                
ff10:012a F4               hlt                                                  
                                                                                
ADDR(LOW) PARAS  OWNER                                                          
009c:0000 0x0014 [FREE]                                                         
00b1:0000 0x0410 [FREE]                                                         
04c2:0000 0x1000 [FREE]                                                         
14c3:0000 0x8b3b [FREE] (END)                                                   
 ~~~

**Comment by andrewbird** [comment]
> Where does it writes the logs when
test succeeds? I'd like to see the local
mcb map.

Normally they are deleted, but I can add a quick commit not to do so.

**Comment by stsp** [comment]
Thanks!
So 9c is the environment segment.
Could you please add a quick commit
that does `set` after dosdebug?
We'll see if maybe some env vars
were added between runs...

**Comment by stsp** [comment]
It would actually be cool if the
test itself (a C code) would do
`system("set");`.
Then we'll see exactly the env
of 9c, rather than of comcom64.

**Comment by stsp** [comment]
But I can add `system("set");` myself too. :)
So why not...

**Comment by andrewbird** [comment]
There's something odd when I run the test locally I see
~~~
ADDR(LOW) PARAS  OWNER                                                          
009c:0000 0x0016 [UNIX - Environment]                                           
00b3:0000 0x0034 [UNIX]                                                         
00e8:0000 0x9f16 [FREE] (END)                                                   
~~~
but in CI I don't see the UNIX process
~~~
ADDR(LOW) PARAS  OWNER                                                          
009c:0000 0x0014 [FREE]                                                         
00b1:0000 0x0410 [FREE]                                                         
04c2:0000 0x1000 [FREE]                                                         
14c3:0000 0x8b3b [FREE] (END)                                                   
~~~

**Comment by stsp** [comment]
OK I found the difference:
`ERRORLEVEL=0`
gets added.
Not sure why `unix.com` is involved.
I'll just make comcom64 to set
`ERRORLEVEL=0` initially.

**Comment by andrewbird** [comment]
> Not sure why unix.com is involved.

it's because I was using it to call out to `echo mcbs | dosdebug`

But for me I was surprised that it didn't appear in the CI's mcbs listing.

**Comment by stsp** [comment]
> There's something odd when I run the test locally I see

I guess this is because you have
some old comcom64, right? I
announced the new developments
recently. If you updated, there wouldn't
be unix.com there now. :)

**Comment by andrewbird** [comment]
Ahh, I have comcom64 from 10th march.

**Comment by stsp** [comment]
I updated comcom64 to set
ERRORLEVEL initially now. I
think this test will pass, we'll
see if I can speed up the building
of a new package.

**Comment by andrewbird** [comment]
Actually just updating to the current comcom64 package, causes the test to fail for me here locally. Perhaps you also have an older comcom64 installed?

**Comment by stsp** [comment]
Yes, you got me on this. :)
I also had an old comcom64,
as hilarious as it sounds...

**Comment by andrewbird** [comment]
At least it explains why CI behaved differently to our local machines!

**Comment by stsp** [comment]
Indeed, that's a good sign.

**Comment by stsp** [comment]
So in this case just remove all the
extra patches, and I'll merge once
it builds.

**Comment by stsp** [comment]
Which you probably already done! :)

**Comment by andrewbird** [comment]
Cool, it looks like it's passing now, thanks!

**Comment by stsp** [comment]
> Cool, it looks like it's passing now, thanks!

You mean comcom64 already built?
https://code.launchpad.net/~stsp-0/+recipe/comcom64-daily
Hmm.

**Comment by andrewbird** [comment]
yes I waited until the PPA updated, tested locally okay, then force pushed to PR

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
