### PR TITLE
Update terminal.c

### PR DESCRIPTION
**Pull request by c-logic**
FULL Color with xterm-color256

### CODE REVIEW

**Comment by stsp** [comment]
Could you please provide
screen-shots for comparison?

**Comment by c-logic** [comment]
Hi,
i like dosemu and I am very glad that it is being developed further. :)
Thank you very much

Thats the correct color assignment on X11-Window [dosemu -X]:
X11 color assign

This is a sample of the unpatched [dosemu -t]:
wrong color assign

and patched version [dosemu -t]:
patched color assign

All this with the condition xterm-color256 (ssh on kitty).

**Comment by stsp** [comment]
OK, good shots, thanks. :)

So about the patch.
First, it has a huge trailing space
error. Please correct that.

Bit 7 of attributes is not always
the intensity bit: that depends on
a bit 3 of Attribute Control register:
https://web.stanford.edu/class/cs140/projects/pintos/specs/freevga/vga/attrreg.htm#10
Please add a check (if blocking
wasn't there before, no need to
care when bit 7 means blinking -
just mask it out).

**Comment by stsp** [comment]
Ah, this is an initialization!
So I guess your patch is correct,
so please just remove the white-space
error.

**Comment by stsp** [comment]
OK, I just removed the white-space errors
and applied the patch.
Thanks!

**Comment by c-logic** [comment]
I had seen it too late :) 👍

**Pull request closed without merging**
