### PR TITLE
CI: Rework CPU tests to use a static reference file

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by andrewbird** [comment]
Clang compiled native binary seems to have a problem.
~~~
subprocess.CalledProcessError: Command '['/home/runner/work/dosemu2/dosemu2/test/cpu/native32', '--common-tests']' died with <Signals.SIGSEGV: 11>
~~~

**Comment by andrewbird** [comment]
Will rework this PR to use a static reference file that is checked in to git.

**Comment by andrewbird** [comment]
Tests okay now, so this should be good to merge.

**Comment by stsp** [comment]
Thanks!
Reference file should be there
indeed, except that IIRC you said
it varies on different CPUs?

**Comment by andrewbird** [comment]
> except that IIRC you said
it varies on different CPUs?

I don't remember, sorry.

**Pull request merged**
