### PR TITLE
travis: disable force_fs_redirect

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by stsp** [comment]
I wonder if I should disable force_redirect
also by default. Or will I be beaten by those
who doesn't load emufs.com? :)

**Comment by andrewbird** [comment]
I think it's fine to disable by default, then only those DOSes that need it (DOS 3 etc) need to reenable as necessary.

**Comment by stsp** [comment]
For old doses it can be put to autoexec.
But I won't rush doing so.
Write support for fatfs will make it
completely painless.

**Comment by andrewbird** [comment]
:smile:

**Pull request merged**
