### PR TITLE
simx86: stop adding TheCPU.mem_base to segment bases.

### PR DESCRIPTION
**Pull request by bartoldeman**
Instead add it in generated code during address calculation. First step to allow 64-bit mem_base in JIT.

### CODE REVIEW

**Comment by bartoldeman** [comment]
For #1839

**Comment by bartoldeman** [comment]
Followup patch using rbp as mem_base is here (still uses TheCPU.mem_base for stack accesses and rep-stringops but nowhere else). I can add that to this PR or start a new one once this has been approved, just let me know.
https://gist.github.com/7d3134b3d1f8cd19c8f1509f8aef5f0c

**Comment by stsp** [comment]
Thanks!
Looks cool. :)
Just wonder how have you made
sure you covered all load/stores?
I haven't found any obvious way
but to look through all ops...

**Comment by bartoldeman** [comment]
For edi->edi+ebp I checked all the 07's that are left in the generator, looks I didn't miss any.
The CPU tester is also pretty thorough for this.

**Pull request merged**
