### PR TITLE
CI: Add test for PIT mode 2

### PR DESCRIPTION
**Pull request by andrewbird**
See #1639

### CODE REVIEW

**Comment by stsp** [comment]
Is this in a weekly/full suite?

**Comment by andrewbird** [comment]
It's in just the usual set. I don't think it's that time costly. We have worse, the libi86 build takes 550 secs.

**Comment by stsp** [comment]
Applied but I don't think
that's the right thing to do.
libi86 does many tests, not
one.
And this one is "undetermined"
so it can trigger something
once, and not trigger the other
time. I'd rather not put it into a
main suite.

**Comment by andrewbird** [comment]
Okay, understood. I'll see about adding a cron job for Github Actions rather than use more minutes on the Travis one.

**Comment by stsp** [comment]
Already failed. :(

**Comment by andrewbird** [comment]
> Already failed. :(

That's my fault, I forgot to give the test batchfile proper DOS line endings so MS-DOS barfed on it.

**Comment by stsp** [comment]
Why it passed the first CI?

**Comment by andrewbird** [comment]
I don't think comcom32 cares and PRs / branch pushes are only tested with FDPP until they are merged into devel.

**Pull request merged**
