### PR TITLE
Travis Test Updates

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by andrewbird** [comment]
This https://travis-ci.com/github/andrewbird/dosemu2/builds/163543103 seems to have the crash with debug info.

**Comment by stsp** [comment]
What comcom32 does it use?
djgpp have changed a lot in recent ubuntu.
Could you please try uploading the known-good
comcom32, or freecom?

**Comment by andrewbird** [comment]
It always uses the latest comcom32 in the PPA
`0.1~alpha1-100-f39bd60+202004032016~ubuntu18.04.1`. This is also the version I'm using locally that has no issues.

**Comment by stsp** [comment]
Would be good to see how freecom works.
Also I wonder if comcom32 package
version changes when djgpp changes.
Can it be that it was rebuilt with
updated djgpp and now differes from
yours?

**Comment by andrewbird** [comment]
My comcom32 is also from the PPA, so I'm sure it's the same package as it has the same date/git version.
I'll see about FreeCOM later, I have to go out now.

**Comment by stsp** [comment]
I know it from same ppa.
But it could be re-built in ppa as
djgpp updated. Only if build time
matches, then it is not a possibility.

**Comment by stsp** [comment]
Another thing to try is not to build
fdpp, but get it from ppa.

**Comment by andrewbird** [comment]
I pushed an update that uses FreeCOM with FDPP, you'll need at least
36a19dc , d884bb2 and e34d3f4

**Comment by stsp** [comment]
Same crash it seems.
So yes, comcom32 is out of any
accusations. emufs.com roo, as
I disabled everything inside it, but
it still crashes.
Now I am testing emufs.com in
autoexec, and that seems to work.

**Comment by stsp** [comment]
This can now be cleaned up and applied.

**Comment by andrewbird** [comment]
Here's the standard config update + some other small fixes. I also left the FDPP debug options in, unless you think it would harm anything?

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
