### PR TITLE
Rsp

### PR DESCRIPTION
**Pull request by stsp**
Add rsp usage to msdos.c.

### CODE REVIEW

**Comment by stsp** [comment]
@jschwartzenberg could you please check
that win31 and alike things are still good?

**Comment by stsp** [comment]
Test failed with this:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/dosemu2/dosemu2/test-imagedir/pcmos.git'
```
Andrew, what can that be?

**Comment by stsp** [comment]
Locally test passes.

**Comment by andrewbird** [comment]
~~~
Test PP-DOS-GIT  PC-MOS build script                                             ... fatal: early EOF
fatal: fetch-pack: invalid index-pack output
ERROR
~~~
Looks to be some sort of transient network failure, as in the same test under MSDOS it succeeds.

**Comment by stsp** [comment]
Can we please not run the tests if
download failed?
Also you may want to look into caching,
which github seems to support. To not
re-download binary blobs.

**Comment by andrewbird** [comment]
I already use the cache for my test binaries, but the pc-mos test is a pull from its git repo so there's no distinct blob.

**Comment by stsp** [comment]
So lets not run tests if d/l failed?

**Comment by andrewbird** [comment]
Okay.

**Comment by jschwartzenberg** [comment]
> @jschwartzenberg could you please check that win31 and alike things are still good?

I think you already fixed win31 as I saw a ticket on that and it works now. Could you give me a hint on "alike things"? I'll give prio to testing those over other things :)

**Comment by stsp** [comment]
From that particular patch, no
more "alike things" are expected.
Please test that dos prompt works
fine, so that you can run multiple
dos boxes with comcom32, switch
them with Alt-Tab, exit comcom32's
etc.

**Comment by stsp** [comment]
If you have some spare time,
probably it would be good to add
more DOSes to install-otherdos
package. Like novel dos or dr-dos
or edr-dos. :)

**Comment by jschwartzenberg** [comment]
> From that particular patch, no more "alike things" are expected. Please test that dos prompt works fine, so that you can run multiple dos boxes with comcom32, switch them with Alt-Tab, exit comcom32's etc.

I couldn't find a quick trick to avoid my window manager intercepting alt+tab, but I could start multiple "MS-DOS Prompt"s minimized and close them in random order, opening new ones in between, without issues. This seems stable.


> Like novel dos or dr-dos
> or edr-dos. :)

Novell DOS, DR-DOS and Caldera OpenDOS are all the same thing with different names. There's OpenDOS already. I could look into adding more versions of it if that would help, but at the time it was tricky to add other ones than the ones shipped as part of Caldera's OpenLinux.

I'm not familiar with EDR-DOS, it might not be covered yet.


> If you have some spare time,

Not sure how much I'll have, but in general I'll keep this in mind :)

**Comment by stsp** [comment]
> I couldn't find a quick trick to avoid my window manager intercepting alt+tab

Ctrl-Alt-k?

**Comment by jschwartzenberg** [comment]
> > I couldn't find a quick trick to avoid my window manager intercepting alt+tab
> 
> Ctrl-Alt-k?

In KDE that shortcut is occupied by default to switch keyboard layouts.

**Comment by stsp** [comment]
Ctrl-Alt-f

**Comment by jschwartzenberg** [comment]
DOSEMU2 goes full screen, but the window manager still captures the other shortcuts, alt+tab, ctrl+alt+k, etc.

**Comment by stuaxo** [comment]
Does Ctrl-Escape work ?

**Comment by jschwartzenberg** [comment]
That brings up the process manager.

**Pull request merged**
