### PR TITLE
Vthr

### PR DESCRIPTION
**Pull request by stsp**
Threaded vtmr & coopth.

### CODE REVIEW

**Comment by stsp** [comment]
Hi Andrew, all tests seem to
be failing because lsan writes
some errors on exit.
Could you please fix that?

**Comment by stsp** [comment]
Disabled lsan for now.

**Comment by andrewbird** [comment]
There are only three tests failing (libi86 build multiple failure is filling the screen), they all use dosemu in non-interactive mode `-E`. The problem is that the dosemu is returning a non-zero error when lsan is used. That's a problem because we need to fail in that condition in order to correctly observe the result of test suite libi86, otherwise we could just ignore the error code returned. Here's the simplest example.
~~~
ajb@polly:/clients/common/dosemu2.git$ env SKIP_EXPENSIVE=1 ./test/test_dos.py PPDOSGITTestCase.test_passing_environment_variable
Test PP-DOS-GIT  Passing Environment Variable to DOS                             ... ERROR

======================================================================
ERROR: Test PP-DOS-GIT  Passing Environment Variable to DOS                            
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test_dos.py", line 4892, in test_passing_environment_variable
    results = self.runDosemuCmdline(args, config="""\
  File "/clients/common/dosemu2.git/test/common_framework.py", line 397, in runDosemuCmdline
    ret = check_output(args, cwd=cwd, timeout=timeout, stderr=STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/clients/common/dosemu2.git/bin/dosemu', '--Fimagedir', '/tmp/test-imagedir', '-f', '/tmp/test-imagedir/dosemu.conf', '-n', '-o', '/clients/common/dosemu2.git/test_dos.PPDOSGITTestCase.test_passing_environment_variable.log', '-td', '-ks', 'TESTVAR1=0123456789aBcDeF', '-q', '-E', 'testit.bat']' returned non-zero exit status 23.

----------------------------------------------------------------------
Ran 1 test in 4.354s

FAILED (errors=1)
~~~

Then if I start dosemu with the same environment from the test instance, and just exit without running any tests I see lots of lsan errors and also the same exit code.

~~~
ajb@polly:/clients/common/dosemu2.git$ ./runstandalonetest.sh 

=================================================================
==68307==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f345bfaf9c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    #1 0x7f345aeb82f4  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x212f4)
    #2 0x7f345aeb89b8  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x219b8)
    #3 0x7f345aeb9fdc  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x22fdc)
    #4 0x7f345aec106c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2a06c)
    #5 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #6 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #7 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #8 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #9 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #10 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #11 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #12 0x7f345aebf58c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2858c)
    #13 0x7f345aebfabe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28abe)
    #14 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #15 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #16 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #17 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #18 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #19 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #20 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #21 0x7f345aeb0f77  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x19f77)
    #22 0x7f345aeb11da  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1a1da)
    #23 0x7f345aea3156  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc156)
    #24 0x7f345aea318c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc18c)
    #25 0x7f345b00c5bf in SDL_text_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:301
    #26 0x7f345b00d8ec in SDL_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:356
    #27 0x5641122d432f in video_post_init /clients/common/dosemu2.git/src/base/video/video.c:447
    #28 0x564112468d42 in iodev_init /clients/common/dosemu2.git/src/base/init/dev_list.c:106

Objects leaked above:
0x610000000500 (256 bytes)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f345bfaf9c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    #1 0x7f345aea2b79  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbb79)
    #2 0x7f345aea56d1 in FcConfigFilename (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xe6d1)
    #3 0x7f345aebf151  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28151)
    #4 0x7f345aebfabe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28abe)
    #5 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #6 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #7 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #8 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #9 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #10 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #11 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #12 0x7f345aebf58c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2858c)
    #13 0x7f345aebfabe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28abe)
    #14 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #15 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #16 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #17 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #18 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #19 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #20 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #21 0x7f345aeb0f77  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x19f77)
    #22 0x7f345aeb11da  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1a1da)
    #23 0x7f345aea3156  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc156)
    #24 0x7f345aea318c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc18c)
    #25 0x7f345b00c5bf in SDL_text_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:301
    #26 0x7f345b00d8ec in SDL_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:356
    #27 0x5641122d432f in video_post_init /clients/common/dosemu2.git/src/base/video/video.c:447
    #28 0x564112468d42 in iodev_init /clients/common/dosemu2.git/src/base/init/dev_list.c:106

Objects leaked above:
0x602000010d60 (24 bytes)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f345bfaf9c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    #1 0x7f345aea2b79  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbb79)
    #2 0x7f345aea56d1 in FcConfigFilename (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xe6d1)
    #3 0x7f345aec0fbe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x29fbe)
    #4 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #5 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #6 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #7 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #8 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #9 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #10 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #11 0x7f345aebf58c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2858c)
    #12 0x7f345aebfabe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28abe)
    #13 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #14 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #15 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #16 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #17 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #18 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #19 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #20 0x7f345aeb0f77  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x19f77)
    #21 0x7f345aeb11da  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1a1da)
    #22 0x7f345aea3156  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc156)
    #23 0x7f345aea318c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc18c)
    #24 0x7f345b00c5bf in SDL_text_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:301
    #25 0x7f345b00d8ec in SDL_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:356
    #26 0x5641122d432f in video_post_init /clients/common/dosemu2.git/src/base/video/video.c:447
    #27 0x564112468d42 in iodev_init /clients/common/dosemu2.git/src/base/init/dev_list.c:106
    #28 0x5641123226c8 in main /clients/common/dosemu2.git/src/base/core/emu.c:359

Objects leaked above:
0x602000010d40 (24 bytes)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f345bfaf9c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    #1 0x7f345b34238e in __GI___strdup /build/glibc-SzIz7B/glibc-2.31/string/strdup.c:42
    #2 0x56411244cdbc in yyparse /clients/common/dosemu2.git/src/base/init/parser.y:985
    #3 0x5641124539a2 in do_parse /clients/common/dosemu2.git/src/base/init/parser.y:2643
    #4 0x564112453af8 in parse_config /clients/common/dosemu2.git/src/base/init/parser.y:2687
    #5 0x56411246474e in config_init /clients/common/dosemu2.git/src/base/init/config.c:1187
    #6 0x5641123225bd in main /clients/common/dosemu2.git/src/base/core/emu.c:303
    #7 0x7f345b2c7082 in __libc_start_main ../csu/libc-start.c:308
    #8 0x5641122c93fd in _start (/clients/common/dosemu2.git/2.0-pre9/bin/dosemu.bin+0x1f93fd)

Objects leaked above:
0x601000000c80 (1 bytes)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f345bfaf712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
    #1 0x7f345aeb893c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2193c)
    #2 0x7f345aeb9fdc  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x22fdc)
    #3 0x7f345aec106c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2a06c)
    #4 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #5 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #6 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #7 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #8 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #9 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #10 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #11 0x7f345aebf58c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2858c)
    #12 0x7f345aebfabe  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x28abe)
    #13 0x7f34572b0a59  (/lib/x86_64-linux-gnu/libexpat.so.1+0xba59)
    #14 0x7f34572b172f  (/lib/x86_64-linux-gnu/libexpat.so.1+0xc72f)
    #15 0x7f34572aeb85  (/lib/x86_64-linux-gnu/libexpat.so.1+0x9b85)
    #16 0x7f34572b00cd  (/lib/x86_64-linux-gnu/libexpat.so.1+0xb0cd)
    #17 0x7f34572b3e3f in XML_ParseBuffer (/lib/x86_64-linux-gnu/libexpat.so.1+0xee3f)
    #18 0x7f345aebef42  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x27f42)
    #19 0x7f345aebf37b  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x2837b)
    #20 0x7f345aeb0f77  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x19f77)
    #21 0x7f345aeb11da  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1a1da)
    #22 0x7f345aea3156  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc156)
    #23 0x7f345aea318c  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0xc18c)
    #24 0x7f345b00c5bf in SDL_text_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:301
    #25 0x7f345b00d8ec in SDL_init /clients/common/dosemu2.git/src/plugin/sdl/sdl.c:356
    #26 0x5641122d432f in video_post_init /clients/common/dosemu2.git/src/base/video/video.c:447
    #27 0x564112468d42 in iodev_init /clients/common/dosemu2.git/src/base/init/dev_list.c:106
    #28 0x5641123226c8 in main /clients/common/dosemu2.git/src/base/core/emu.c:359

Objects leaked above:
0x60200001f4a0 (32 bytes)

SUMMARY: LeakSanitizer: 337 byte(s) leaked in 5 allocation(s).
ajb@polly:/clients/common/dosemu2.git$ echo $?
23
~~~

So it seems to me that lsan, if it finds errors, indicates the case via the process error code 23. I think I need to be a little bit more selective if I'm going to ignore error codes, so I'll look for the `LeakSanitizer` string in the output also.

I created something that works for two of the three tests, but it seems that libi86 also doesn't like dosemu returning 23 instead of 0.

~~~
../../tests/metacheck.at:41: exit code was 23, expected 0                       
3. metacheck.at:38: 3. dosemu (metacheck.at:38): FAILED (metacheck.at:41) 
<snip>

ERROR: 88 tests were run,                                                       
86 failed unexpectedly.                                                         
4 tests were skipped.                                                           
~~~

I'm not sure there's anything I can do about that.

**Comment by andrewbird** [comment]
Here's the PR https://github.com/dosemu2/dosemu2/pull/1663 , but of course it'll still fail. I also looked for a way to disable LeakSanitizer at runtime, but didn't see anything.

**Comment by stsp** [comment]
Thanks for info, I disabled
the exitcode feature now.
Does this help?

**Comment by andrewbird** [comment]
That works for me here, so I think you may as well re-enable lsan in the config now.

**Comment by andrewbird** [comment]
BTW I'm just adding a test to check that DOS errors do propagate to Dosemu's return code. I noticed that this only works with FDPP/comcom32 is that expected?

**Comment by stsp** [comment]
At least IIRC freecom indeed
swallows the error code. But
not sure about the MS command.com.
Everything works properly with
4dos for sure.

**Pull request merged**
