### PR TITLE
Ttf

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by stsp** [comment]
IMHO now that looks super-cool!
Everyone is encouraged to try and see. :)

**Comment by andrewbird** [comment]
I didn't get the chance to actually try this out yet, but it looks good. I'm glad you are working on this, hopefully it'll be good enough to merge at last.

**Comment by stsp** [comment]
Just try to switch between fullscreen
and windowed mode a few times!
I am not sure if your WM supports the
smooth resize, but, during that smooth
resize, dosemu2 changes font (not only
size, but font!), and you can't even notice
that.
Just can't stop pressing Ctrl-Alt-f here. :)
Of course the manual resize with mouse
is not at all that smooth, but its quite
acceptable too.

**Comment by andrewbird** [comment]
Cool, it looks really nice (even with a 2005 graphics card!)

**Comment by stsp** [comment]
I thought modern WMs refuse to work with
a graphics cards w/o compositor-specific
opengl features.

**Comment by andrewbird** [comment]
> I thought modern WMs refuse to work with
a graphics cards w/o compositor-specific
opengl features.

I've not had to do anything specific to make it work, just regular {X,L}ubuntu installs. I know it won't run some things like the OpenGL based terminal 'alacritty', but other OpenGL stuff seems to work like glxgears etc. Perhaps my card is on the cusp of support and I'm just lucky.
~~~
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV516 [Radeon X1300/X1550 Series]
01:00.1 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] RV516 [Radeon X1300/X1550 Series] (Secondary)
~~~

**Comment by stefand** [comment]
Just to add more 2c to a dead git branch: Only Gnome 3 insists on compositing. KDE, xfce, and obviously smaller WMs like fvwm and twm work just fine without any OpenGL. I just updated my old laptop with an even older GPU:

01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV250/M9 GL [Mobility FireGL 9000/Radeon 9000] (rev 01)

Works just fine with a modern (20.12) Plasma Desktop. I have compositing off for now, but last time it had a compositing codepath that worked on that card too. HW acceleration of OpenGL 1.4 plus a pile of newer extensions (framebuffers, vertex programs) work on that device.

Now I can toy around with proper vm86 :-)

**Comment by stsp** [comment]
Ok so we already have 2 examples
where the top-most requirements do
not mean the best product. :)

**Pull request merged**
