### PR TITLE
CI: Add install_freedos test

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
downloaddos is called from
`dosemu-installfreedosuserspace`.
It would be good to test that full
installation works, and that
`dosemu -E mem` does what
is expected.

**Comment by andrewbird** [comment]
Even just the download test takes ~1200 secs at GitHub. The same test is completed in under 60 secs locally. I think external bandwidth at GitHub is intentionally crippled. Probably this makes the test unworkable.

**Comment by stsp** [comment]
Maybe add --check-only mode
so that wget only checks that the
files are available?
And at the end, D/L one file and
check `dosemu -E mem`

**Comment by andrewbird** [comment]
The script doesn't use wget, it uses python urllib module instead. Maybe that's an option there too, but changes will need to be done to the install-freedos tool itself, rather than anything I can do in the test suite.

**Comment by stsp** [comment]
Found this on internet:
```
def is_urlfile(url):
    # Check if online file exists
    try:
        r = urllib.request.urlopen(url)  # response
        return r.getcode() == 200
    except urllib.request.HTTPError:
        return False
```

**Comment by andrewbird** [comment]
Perhaps @jschwartzenberg can add it to the install-freedos repo?

**Comment by stuaxo** [comment]
You can do a HEAD request just for the http header, instead of GET, check that you get a 200.

I've used this before in a different context to check stuff like the etag on an S3 bucket.

It's pretty likely that github gives you other useful metadata as well.

EDIT:  Read the code from @stsp it's possible that this does the same thing, I'd probably need to beak out a proxy and postman to check though.

**Comment by stsp** [comment]
In a mean time, could you please
make CI to run with asan enabled?
That would be really cool, as currently
I have asan disabled, its too slow.
But with CI it would be perfectly
fine to have it disabled locally.
I propose to have a separate
compiletime-settings preset for CI.

**Comment by andrewbird** [comment]
Like this https://github.com/andrewbird/dosemu2/commit/179b640610639baaebab4c5b60de9beb1ce997b6. Is there any difference between using `-d` and specifying `compiletime-settings.devel` that I might be now be missing?

**Comment by andrewbird** [comment]
Ohh CI failing majorly!

**Comment by stsp** [comment]
Except that -d no longer enables asan,
and that's the whole point.
Enabling sanitizers, even for devel builds,
proved to be hard, as it produces very
slow and barely usable dosemu.
And I dont quite want to dualboot:
dosemu for debugging and dosbox
for some dosing. :)

**Comment by andrewbird** [comment]
> Except that -d no longer enables asan,
and that's the whole point.

Yes I get that, I just wondered if `-d` caused anything else other than to use the devel config.

There's probably lots of asan shown things to be fixed before I can enable this, the number of failures is horrific as is the test time (4 fold increase). See https://github.com/andrewbird/dosemu2/actions/runs/2561350883

**Comment by stsp** [comment]
` AttributeError: 'NoneType' object has no attribute 'group'`
is what the errors are saying.  So not too much
to fix on my side.
Besides, asan was enabled for -d for quite long.

**Comment by andrewbird** [comment]
> AttributeError: 'NoneType' object has no attribute 'group'
is what the errors are saying.

Yes those three ERRORs are now fixed, I expect they'll now be FAILs instead. 

I see a lot of dosemu non zero exit codes with asan. I'm thinking the real problem might be that, or test timeout due to slowness, or perhaps both.

Download the `failure-logs.zip` and let's just consider one test for now `test_dos.PPDOSGITTestCase.test_passing_environment_variable` look at its `xpt` and `log` files. It's definitely exiting with code 6, which will cause the failure at least in this test. I remember you did something for lsan to stop this, is there something similar for asan?

**Comment by andrewbird** [comment]
I also think this may be significant, it seems to be in many logs
~~~
msdos_ldt.c:264:48: runtime error: applying non-zero offset 65536 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior msdos_ldt.c:264:48 in 
==65659==AddressSanitizer CHECK failed: /build/llvm-toolchain-10-yegZYJ/llvm-toolchain-10-10.0.0/compiler-rt/lib/asan/asan_interceptors.cpp:333 "((__interception::real___cxa_throw)) != (0)" (0x0, 0x0)
    #0 0x55a2db69759e in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/runner/work/dosemu2/dosemu2/2.0-pre9/bin/dosemu.bin+0x61559e)
    #1 0x55a2db6ababf in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/runner/work/dosemu2/dosemu2/2.0-pre9/bin/dosemu.bin+0x629abf)
    #2 0x55a2db67a5e0 in __interceptor___cxa_throw (/home/runner/work/dosemu2/dosemu2/2.0-pre9/bin/dosemu.bin+0x5f85e0)
    #3 0x7fe004cbf7ed in fdpp_noret(int) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./dispatch.hpp:60:5
    #4 0x7fe004cbf7ed in asm_call_noret(vm86_regs*, unsigned short, unsigned short, unsigned char*, unsigned char) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:509:5
    #5 0x7fe004cbf7ed in _call_wrp(void (*)(vm86_regs*, unsigned short, unsigned short, unsigned char*, unsigned char), vm86_regs*, unsigned short, unsigned short, unsigned char*, unsigned char) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:445:5
    #6 0x7fe004cbf7ed in _do_asm_call_far(int, unsigned char*, unsigned char, void (*)(vm86_regs*, unsigned short, unsigned short, unsigned char*, unsigned char)) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:455:13
    #7 0x7fe004cbf7ed in do_asm_call(int, unsigned char*, unsigned char, int) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:517:15
    #8 0x7fe004cbf7ed in call_p_0(FarPtr<config>) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./thunk_asms.h:202:1
    #9 0x7fe004ca9458 in kernel() /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/main.cc:583:3
    #10 0x7fe004ca9458 in FreeDOSmain() /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/main.cc:182:3
    #11 0x7fe004cba946 in int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()::operator()() const /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./dispatch.hpp:51:13
    #12 0x7fe004cba946 in  std::__invoke_impl<int, int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()&>(std::__invoke_other, int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14
    #13 0x7fe004cba946 in std::enable_if<__and_<std::__not_<std::is_void<> >, std::is_convertible<std::__invoke_result<int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()&>::type> >::value>::type std::__invoke_r<int, int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()&>(int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:141:14
    #14 0x7fe004cba946 in std::_Function_handler<int (), int fdpp_dispatch_v<>(DispStat*, void (*)())::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:291:9
    #15 0x7fe004cba946 in std::function<int ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_function.h:622:14
    #16 0x7fe004cba946 in int _dispatch<int>(DispStat*, std::function<int ()>) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./dispatch.hpp:29:15
    #17 0x7fe004cba946 in int fdpp_dispatch_v<>(DispStat*, void (*)()) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./dispatch.hpp:48:12
    #18 0x7fe004cba946 in FdppThunkCall(int, unsigned char*, DispStat*, int*) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/./thunk_calls.h:14:3
    #19 0x7fe004cba946 in _FdppCall(vm86_regs*) /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:338:15
    #20 0x7fe004cba946 in FdppCall /home/runner/work/dosemu2/dosemu2/localfdpp.git/fdpp/thunks.cc:369:11
    #21 0x7fe0050914aa in fdpp_thr /home/runner/work/dosemu2/dosemu2/src/plugin/fdpp/hooks.c:49:15
    #22 0x55a2db7bcf67 in coopth_thread /home/runner/work/dosemu2/dosemu2/src/base/core/coopth.c
    #23 0x55a2db852a1b in co_runner /home/runner/work/dosemu2/dosemu2/src/base/lib/libpcl/pcl.c:77:2

==65659==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fdff6d00500; bottom 0x7fe0078e7000; size: 0xffffffffef419500 (-280914688)
~~~

**Comment by stsp** [comment]
I think there are 2 unrelated errors:
```
msdos_ldt.c:264:48: runtime error: applying non-zero offset 65536 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior msdos_ldt.c:264:48 in 
```
This seems to be from ubsan.
Can you check if both are clang-specific?
Never seen those.

**Comment by andrewbird** [comment]
With dosemu compiled with gcc, I don't see those errors here. Also many more tests pass again.

**Comment by stsp** [comment]
So how to reproduce this off-line?

**Comment by andrewbird** [comment]
Just build as you like, clang or gcc, with or without asan, then run the following in the dev directory
~~~
./test/test_dos.py PPDOSGITTestCase.test_passing_environment_variable
~~~

**Comment by andrewbird** [comment]
That one fails on both clang and gcc with asan, but ok on both without asan.

**Comment by stsp** [comment]
This one is the asan bug.
I wonder about the clang-specific one.
As maybe clang triggers something new.

**Comment by andrewbird** [comment]
I'll have to look at the logs again for an example.

**Comment by stsp** [comment]
Seems like I can reproduce it w/o
any examples. :)

**Comment by andrewbird** [comment]
cool, thanks, saves me a job!

**Comment by stsp** [comment]
I fixed the ubsan support, but
asan is now broken by this:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428
So I suppose asan is permanently
broken and should not be enabled...
Which is quite a shame because with
valgrind things are 10 times slower.

**Comment by stsp** [comment]
I worked around the asan problem
so it can now be enabled for a test.

But more importantly, I think we miss
the ubsan errors, that is always enabled.
You occasionally noticed it because
also asan failed. Would it be possible
to make sure that we have no ubsan
errors during tests?

**Comment by stsp** [comment]
I think basically any stderr
output should be alerted.
What do you think?

**Comment by stsp** [comment]
Hmm, it seems these ubsan
errors were not reproducible
without also enabling asan...
So we probably do not miss
any errors right now.
But I can't be certain.
Would a random stderr msg
be alerted on CI?

**Comment by andrewbird** [comment]
Stderr itself won't cause the test itself, but we can test for specific strings in it and fail on those. It might take a bit of figuring out what to look for.

**Comment by stsp** [comment]
> Stderr itself won't cause the test itself

What do you mean?
I think it should just cause the failure,
because normally we have no stderr
output.

**Comment by andrewbird** [comment]
I'll have to check this out.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/runs/7064138536?check_suite_focus=true#step:7:36453
Any reason why all tests have failed?

**Comment by andrewbird** [comment]
Ahh the first run of the github actions cron job. It's a wider scope test than usual.

> Any reason why all tests have failed?

Not all, two distinct groups:
 - share semantics
   - DR-DOS are different to MS-DOS 6.22 with regard to one/two process compat
   - FR-DOS 1.20 not perfect either, I need to skip those
 - libi86 tests got recently renamed and forgot to think about how to skip them on known bad platforms (FreeDOS 1.20)

I'll work on cleaning this up, but in the meantime it won't affect the usual tests, they should run just fine.

**Comment by stsp** [comment]
> DR-DOS are different to MS-DOS 6.22 with regard to one/two process compat

Maybe we shouldn't be following the
crappy msdos semantic then?
Please study the 2 approaches and
make a decision which one we should
follow. :)

**Comment by andrewbird** [comment]
After your latest asan fixes, just one test now failing
```./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative```

with the dosemu,conf settings in this test, dosemu wont even get to the DOS prompt for me if I start it outside the test.
~~~
$_force_fs_redirect = (off)                                                     
$_hdimage = "dXXXXs/c:hdtype1 +1"                                               
$_floppy_a = ""                                                                 
$_cpu_vm = "emulated"                                                           
$_cpu_vm_dpmi = "native"                                                        
$_cpuemu = (0)                                                                  
$_ignore_djgpp_null_derefs = (off)                                              
~~~

~~~
ERROR: Fault handler re-entered! signal=11 _trapno=0xE                          
System info:                                                                    
==4118==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7f910e26a200; bottom 0x7f9110e62000; size: 0xfffffffffd408200 (-46104064)
~~~

**Comment by stsp** [comment]
```
$ ./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative
Traceback (most recent call last):
  File "/home/stas/src/dosemu2/./test/test_dos.py", line 5111, in <module>
    libi86_create_items(OurTestCase)
  File "/home/stas/src/dosemu2/test/func_libi86_testsuite.py", line 16, in libi86_create_items
    listing = check_output([TESTSUITE, '--list'])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/ia16-elf/libexec/libi86/tests/testsuite'
```

But is this test libi86-related?

**Comment by andrewbird** [comment]
> But is this test libi86-related?

Yes you don't have the package libi86-testsuite-ia16-elf installed. If you haven't got access to that you can probably comment out 
~~~
libi86_create_items(OurTestCase)
~~~
In the main function of test.py

**Comment by stsp** [comment]
But I thought PPDOSGITTestCase.test_cpu_2_jitnative
runs our djgpp-compiled cpu tests?
Why libi86 here?

**Comment by andrewbird** [comment]
> Why libi86 here?

It's nothing to do with the test you specified, libi86 tests are defined dynamically now as otherwise I'd have to define and maintain function calls for 93 tests. That said I'm just working on making the package optional, obviously the tests won't be available if the package is missing.

**Comment by stsp** [comment]
libi86-testsuite-ia16-elf installed.
Now:
```
$ ./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative
Test PP-DOS-GIT  CPU test: JIT vm86 + native DPMI                                ... skipped "Unable to build test binaries 'Command '['make', '-C', '/home/stas/src/dosemu2/test/cpu', 'all']' returned non-zero exit status 2.'"

----------------------------------------------------------------------
Ran 1 test in 1.658s

OK (skipped=1)
```

**Comment by andrewbird** [comment]
Run it by hand, to see what you are missing
make -C test/cpu clean all

**Comment by stsp** [comment]
Thanks, that helped, had to
install multilib libc6-dev.
Anyway:
```
$ ./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative
Test PP-DOS-GIT  CPU test: JIT vm86 + native DPMI                                ... ok (  1.01s)

----------------------------------------------------------------------
Ran 1 test in 1.014s

OK
```

**Comment by stsp** [comment]
Though I haven't used your
dosemurc settings. Should I?

**Comment by stsp** [comment]
I guess so. :)

**Comment by stsp** [comment]
Well, doesn't matter what I put
to dosemurc because tests use
their own...
So not sure how to reproduce this.

**Comment by andrewbird** [comment]
> Well, doesn't matter what I put
to dosemurc because tests use
their own...

Correct

I didn't see this error before I enabled asan, is your dosemu built with that?

**Comment by stsp** [comment]
No sir... :)
However:
```
$ ./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative
Test PP-DOS-GIT  CPU test: JIT vm86 + native DPMI                                ... FAIL
Traceback (most recent call last):
  File "/home/stas/src/dosemu2/./test/test_dos.py", line 5170, in <module>
    main(argv)
  File "/home/stas/src/dosemu2/test/common_framework.py", line 528, in main
    unittest.main(testRunner=MyTestRunner, argv=argv, verbosity=2)
  File "/usr/lib/python3.10/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.10/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 599, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/lib/python3.10/unittest/case.py", line 516, in _feedErrorsToResult
    result.addFailure(test, exc_info)
  File "/home/stas/src/dosemu2/test/common_framework.py", line 437, in addFailure
    self.failures.append((test, self.gather_info_for_failure(err, test)))
  File "/home/stas/src/dosemu2/test/common_framework.py", line 455, in gather_info_for_failure
    length = self._count_relevant_tb_levels(tb)
AttributeError: 'MyTestResult' object has no attribute '_count_relevant_tb_levels'. Did you mean: '_is_relevant_tb_level'?
```

**Comment by andrewbird** [comment]
Oh dear, it seems my overriding of certain parts of the unittest module for better formatting has been scuppered by some internal changes to that module in a newer python version. It was probably a bad idea to do it that way. 

For now, we'll have to work around that on your system. Do
~~~
$ ./test/test_dos.py PPDOSGITTestCase.test_cpu_2_jitnative
~~~
to setup the test, then
~~~
$ bin/dosemu -n -f test-imagedir/dosemu.conf -o test.log --Fimagedir `pwd`/test-imagedir
~~~

Which should give you a interactive DOS session. You can run the `testit.bat` file to run the test.

**Comment by stsp** [comment]
Seems like that long-standing
nodelinker instability finally caught.
With this:
```
--- a/src/base/emu-i386/simx86/codegen-x86.c
+++ b/src/base/emu-i386/simx86/codegen-x86.c
@@ -3101,7 +3101,7 @@ void NodeUnlinker(TNode *G)
                leavedos_main(0x8116);
            }
            B = B->next;
-           free(b2);
+//         free(b2);
        }
 
        if (T->nrefs) {
@@ -3123,7 +3123,7 @@ void NodeUnlinker(TNode *G)
                if (*Bt->ref==G) {
                        Btq->next = Bt->next;
                        Gt->clink.nrefs--;
-                       free(Bt);
+//                     free(Bt);
                        break;
                }
                Btq = Bt;
@@ -3145,7 +3145,7 @@ void NodeUnlinker(TNode *G)
                if (*Bn->ref==G) {
                        Bnq->next = Bn->next;
                        Gn->clink.nrefs--;
-                       free(Bn);
+//                     free(Bn);
                        break;
                }
                Bnq = Bn;
```

you can avoid the problem.
@bartoldeman maybe you can take
a look? :) There is probably some
double-free here, but asan crashes
on trying to unwind the jit-generated
stack.

**Comment by stsp** [comment]
OTOH it probably doesn't
indicate any bug. It seems
asan just grabs a stack trace
for any free(), for the later
use if something bad happens.

**Comment by stsp** [comment]
I created a w/a for this in a
separate branch.
Could you please check how
it goes now?

**Comment by andrewbird** [comment]
rebased t21 on your asfix branch https://github.com/andrewbird/dosemu2/runs/7081961236?check_suite_focus=true

**Comment by andrewbird** [comment]
> Could you please check how
it goes now?

Fixes it for me locally.

**Comment by stsp** [comment]
Converted to PR.
But I am currently away from
my main machine, and this
change needs a bit of testing.

**Comment by stsp** [comment]
I wonder how large projects
survive, if the project as small
as dosemu2 is, suffers such a
pressure from tool-chain bugs.
No matter what you do, you
break gcc or gdb. asan has so
many problems up to being
useless (not to mention that
all of these problems are reported
and fully studied long ago).
gcc still doesn't produce a
working fdpp, nasm still doesn't
have SEGRELATIVE relocs,
and so on and so forth.
Unbelievable conditions for a
21st century. :)

**Comment by andrewbird** [comment]
I'm thinking that we should probably just do a single weekly test with asan enabled, otherwise it'll make testing really sluggish. Is that reasonable?

**Comment by stsp** [comment]
Sure enough.

**Comment by jschwartzenberg** [comment]
> Perhaps @jschwartzenberg can add it to the install-freedos repo?

I missed this somehow. I think some logic to just test URLs instead of downloading should be fine yep. It will take a bit more work, I will probably add it when there's another breakage so I can fix it TDD style :)

**Pull request closed without merging**
