### PR TITLE
Update comcom32 dependency to make dosemu2 installable

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
0.1~alpha2 is the correct versioning for comcom32 library,
not 0.1alpha2 (that is a non-existent version)

This fixes dosemu2 uninstallability in Ubuntu ppa

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Closing because of 016dc4e7153828d875073fffbde36d58effa69dc

**Comment by andrewbird** [comment]
I'm not sure what's going on with [launchpad](https://code.launchpad.net/~dosemu2/+recipe/dosemu2-daily) at the moment. I sync'd it with the git repo, and then triggered a recipe build, but although the source packages have been built, the binaries are still in the scheduled state. It seems to vary the estimate to start between 8 and 25 minutes. So until this happens the PPA package of dosemu is not installable.

**Comment by andrewbird** [comment]
At last they are building...

**Comment by andrewbird** [comment]
They are now built, but not yet published...

**Comment by andrewbird** [comment]
Finally after 3 hours it's now okay.

**Comment by LocutusOfBorg** [comment]
We had an Ubuntu issue with the farm, and Britney and publisher were crashing during runs... :)

**Pull request closed without merging**
