### PR TITLE
Test

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by stsp** [comment]
Hi Andrew, could you please speed
up the pcmos test-case by adding the
tarred git archive to test-binaries,
and only having the test to do
`git pull` instead of `git clone`?

Also it would be good to move the
`PIT Mode 2` test to weekly, as its a
time hog.

**Comment by andrewbird** [comment]
> Hi Andrew, could you please speed
up the pcmos test-case by adding the
tarred git archive to test-binaries,
and only having the test to do
git pull instead of git clone?

I will try to do it later. 

> Also it would be good to move the
PIT Mode 2 test to weekly, as its a
time hog.

It's already only done on the 'full' test done weekly.

Are you seeing the slowness problem locally? If you are then try doing `env SKIP_EXPENSIVE=1 test/test_dos.py PPDOSGITTestCase`  which should skip both of the above.

**Comment by stsp** [comment]
> SKIP_EXPENSIVE=1 test/test_dos.py PPDOSGITTestCase which should
> skip both of the above.

Thanks, that trick actually works.
I think it would be possible to return
pcmos test to the "inexpensive"
category, because `git clone` is a
problem there.

**Comment by stsp** [comment]
Also with this topic merged, I've
finally got tests passed locally!
For the first time.

**Comment by andrewbird** [comment]
> I think it would be possible to return
pcmos test to the "inexpensive"
category

I'll see how much of a speed up we get by untarring vs git clone.

So `shldw` is not required to be tested any more?

**Comment by stsp** [comment]
shldw is still tested, you can still grep
it in the log.

**Pull request merged**
