### PR TITLE
Dremot

### PR DESCRIPTION
**Pull request by stsp**
New DPMI back-end!
But quite slow as yet...

### CODE REVIEW

**Comment by andrewbird** [comment]
How do I enable this remote DPMI thingy? It didn't seem to be built automatically as when I attempted to select it I got
~~~
ERROR: /clients/common/dosemu2.git/2.0-pre9/bin/libplugin_dremote.so: /clients/common/dosemu2.git/2.0-pre9/bin/libplugin_dremote.so: cannot open shared object file: No such file or directory
ERROR: Native DPMI not compiled in                                              
ERROR: DPMI initialization failed, exiting                                      
~~~

So I tried adding 'dremote' to `plugin_list` and then during build I got
~~~
make[2]: Entering directory '/clients/common/dosemu2.git/src'
make[2]: *** plugin/dremote: No such file or directory. Stop.
make[2]: Leaving directory '/clients/common/dosemu2.git/src'
make[1]: *** [/clients/common/dosemu2.git/src/arch/linux/Makefile.main:119: plugin/dremote] Error 2
make[1]: Leaving directory '/clients/common/dosemu2.git/src'
make: *** [Makefile:28: default] Error 2
~~~

**Comment by stsp** [comment]
I think on CI it builds just fine.
Please show you configure session.

**Comment by andrewbird** [comment]
Just trying again, I see you added 'libseccomp-dev' to the build requirements so as I didn't have it that may be the problem. If not I'll post the log, thanks.

**Comment by stsp** [comment]
Please note that you can run individual
configure in the appropriate plugin dir
to not paste or look at the big log.

**Comment by andrewbird** [comment]
Yes, it was the missing dev package.
~~~
ajb@calypso:/clients/common/dosemu2.git$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
 
Test PP-DOS-GIT  CPU JIT vm86 + JIT DPMI                                         ... ok (  1.87s)
Test PP-DOS-GIT  CPU JIT vm86 + KVM DPMI                                         ... ok (  1.75s)
Test PP-DOS-GIT  CPU JIT vm86 + native DPMI                                      ... ok (  1.64s)
Test PP-DOS-GIT  CPU JIT vm86 + remote DPMI                                      ... ok (  1.83s)
Test PP-DOS-GIT  CPU KVM vm86 + JIT DPMI                                         ... ok (  1.79s)
Test PP-DOS-GIT  CPU KVM vm86 + KVM DPMI                                         ... ok (  1.84s)
Test PP-DOS-GIT  CPU KVM vm86 + native DPMI                                      ... ok (  1.73s)
Test PP-DOS-GIT  CPU KVM vm86 + remote DPMI                                      ... ok (  1.86s)
Test PP-DOS-GIT  CPU KVM vm86 + simulated DPMI                                   ... ok (  2.26s)
Test PP-DOS-GIT  CPU native vm86(i386 only) + native DPMI                        ... skipped 'native vm86() only on 32bit x86'
Test PP-DOS-GIT  CPU native vm86(i386 only) + remote DPMI                        ... skipped 'native vm86() only on 32bit x86'
Test PP-DOS-GIT  CPU simulated vm86 + KVM DPMI                                   ... ok (  1.70s)
Test PP-DOS-GIT  CPU simulated vm86 + native DPMI                                ... ok (  1.72s)
Test PP-DOS-GIT  CPU simulated vm86 + remote DPMI                                ... ok (  2.00s)
Test PP-DOS-GIT  CPU simulated vm86 + simulated DPMI                             ... ok (  2.29s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... ok (  1.68s)
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... ok (  2.77s)

----------------------------------------------------------------------
Ran 17 tests in 29.007s

OK (skipped=2)
~~~

**Comment by stsp** [comment]
Tests are good, but it would be
interesting to know how it feels
performance-wise.
At least I made Jazz Jackrabbit
very fast: much faster than it was
on native DPMI a week ago. :)
Probably the first time in dosemu2
history when I spent time on optimizations,
rather than on quickly adding some
other feature.

**Comment by stsp** [comment]
I don't know if we need such CI
tests right now: I am planing to
replace native DPMI with that one,
so the tests would be inherited.

**Comment by andrewbird** [comment]
> Tests are good, but it would be
interesting to know how it feels
performance-wise.

I can't say as I don't actually use Dosemu for anything myself. 

> I don't know if we need such CI
tests right now

Sure, it was an excuse for me to refactor the cpu tests. I'd been meaning to do it for a while now, but kept putting it off. The 'remote' tests were in a followup commit that can easily be dropped, see https://github.com/andrewbird/dosemu2/commits/ci-117/

> Probably the first time in dosemu2
history when I spent time on optimizations,
rather than on quickly adding some
other feature.

Perhaps it's because people(me!) are being quiet at the moment, that you can get on with what you desire.

**Comment by stsp** [comment]
> I can't say as I don't actually use Dosemu for anything myself.

Play some game.
But don't compare to dosbox-staging. :)

> Perhaps it's because people(me!) are being quiet at the moment, that you can get on with what you desire.

Just because remote DPMI was so
slow initially that I had to start optimizing
things. :)
But its a good step towards secure
design. As you can see it already has
seccomp filter around it.

**Comment by stsp** [comment]
Hi Andrew, would it be possible to
allow `ERROR: Native DPMI not compiled in`
on focal? Otherwise it now fails:
https://github.com/dosemu2/dosemu2/actions/runs/12110023736/job/33759822452

**Comment by andrewbird** [comment]
okay, will look later when I get back home

**Pull request merged**
