### PR TITLE
CI: Updates

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
Would it be possible to use
some tags in commit msg to
trigger those when needed?

**Comment by andrewbird** [comment]
I would think so, I'll try soon.

**Comment by andrewbird** [comment]
I added the commit message [full ci] keyword now.

**Comment by andrewbird** [comment]
This should be good to merge now

**Comment by stsp** [comment]
OK, thanks!

**Pull request merged**
