### PR TITLE
mapping: support alias size in update_aliasmap() [#1955]

### PR DESCRIPTION
**Pull request by stsp**
Since alias sizes are now larger than the first Mb, we can't rely on an identity mapping. So add a new function do_find_hardware_ram() that translates va to pa.
With that, the aliasmap of mem_base now includes ext_mem.

### CODE REVIEW

**Comment by bartoldeman** [comment]
this change fails
`test/test_dos.py PPDOSGITTestCase.test_memory_xms`
I'll have a look why

**Comment by bartoldeman** [comment]
the test passes in the end, I think something out of sync in my setup, nevermind

**Comment by bartoldeman** [comment]
Actually I think I have a better way in the end:

by splitting mmap_kvm into an mmap_kvm that only  modifies the page tables(GVA->GPA) in KVM, and mmap_kvm_pa that does the ioctl (GPA->HVA), register_hardware_ram_virtual2 can call mmap_kvm, and can then be called any time (not just at init).

Then we can call register_hardware_ram_virtual2 and unregister_hardware_ram from xms.c as well, and we can pass SHM for both extmem (from init.c) and XMS (from xms.c), and it'll be registered properly in register_hardware_ram_virtual2.

It's in draft state now though, still working that out properly.

**Comment by stsp** [comment]
But does this somehow affect this
patch that only adds the proper
alias_size support?

**Review by bartoldeman — APPROVED** [review]
approved

**Comment by bartoldeman** [comment]
It's just that with #1955 in this functionality wouldn't actually used at runtime. But that doesn't hurt and it may still be useful in the future, so we can just keep it.

**Pull request merged**
