### PR TITLE
Travis ci 24

### PR DESCRIPTION
**Pull request by andrewbird**
Hopefully you should see here that the full gamut of tests is done, whereas in my topic branch only fdpp was.

### CODE REVIEW

**Comment by andrewbird** [comment]
So @stsp did you have a look at this PR and see the differing test coverage used between personal topic branch and PR? Obviously for you to see the reduced scope testing yourself you'd have to push to a topic branch, then when ready create a PR to merge to devel. So it would be a change in workflow for you to see the benefit, otherwise things would continue with the full test.

**Comment by andrewbird** [comment]
Topic branch test https://travis-ci.com/github/andrewbird/dosemu2/builds/180533606 ~9 minutes
Merge PR test https://travis-ci.com/github/dosemu2/dosemu2/builds/180533614 ~34 minutes

**Comment by stsp** [comment]
Thanks!
9 mins is much better than half an hour.

**Comment by andrewbird** [comment]
Potentially I could split into three levels:
when                                                         | what
---------------------------------------------------- | -------
push to topic branch                                  | fdpp
push to devel and PR merge test to devel | fdpp + msdos
cron test of devel                                       | fdpp + msdos + freedos + drdos + ...

Travis implements the cron job, but granularity is daily, weekly, monthly and no control over time of day it runs

**Comment by stsp** [comment]
Sounds marvellous!
Daily should be enough, hope it is
disabled when no commits are done.

**Pull request merged**
