### PR TITLE
Travis: Only test pushes to devel branch

### PR DESCRIPTION
**Pull request by andrewbird**
Test

### CODE REVIEW

**Comment by stsp** [comment]
I think all PR should be checked.
We can instead save on the checking
of the merges to devel. For example,
already checked PR does not need to
be re-checked once applied to devel.
WRT CI pressure that seems to be
similar to what you do: also reduces
to 1 check per PR.

**Comment by andrewbird** [comment]
Yes, I agree. It seemed wrong to ask you to merge unchecked PRs to devel only to find out when applied if they break something. The situation I'd like to avoid though is when PR has been raised, each push to its source branch generates a new test. That's why I was thinking about having a tag we could place in the commit message when a test was needed. It's the opposite to Travis's standard `[skip ci]` tag.

I'm just experimenting at the moment, but I can't figure out what I'm doing as I don't seem to be generating any jobs. Note I have the `exit 1` in there at the moment so that if I do start a job the build will fail early.

**Comment by stsp** [comment]
Ideally the PR should only be checked
when it was just created. Pushes to PR
should not provoke a re-build, but rather
just to say "all tests failed". To re-trigger
you should close and re-open the PR.
Then we will avoid CI on every push.
But I am not sure if you can implement
that.

**Comment by andrewbird** [comment]
Nothing of value here.

**Pull request closed without merging**
