### PR TITLE
instremu: replace asm that calculates EFLAGS

### PR DESCRIPTION
**Pull request by bartoldeman**
Calculate flags in the same way as codegen-sim.c.

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
You are the King. :)
Let me see how it builds on arm now...
(for libinstr_dec)

**Comment by stsp** [comment]
Broke mfs test somehow...
Though I am not yet sure this patch
is even guilty. Will look.

**Comment by stsp** [comment]
Hi Andrew, any idea why on CI we have this:
```
 Debug info:
gdb /home/runner/work/dosemu2/dosemu2/2.0-pre9/bin/dosemu.bin
attach 27866
info registers
thread apply all backtrace full
detach
quit
```
and the log finishes?
Essential debug info is not being logged,
the gdb run is not visible.
Can that be fixed?
https://github.com/dosemu2/dosemu2/actions/runs/4561319903/jobs/8047143213

**Comment by andrewbird** [comment]
Is there anything I can do to make dosemu trigger the run of gdb for testing?

**Comment by stsp** [comment]
`killall -SEGV dosemu.bin`.

**Comment by andrewbird** [comment]
I added a tweak to capture the gdb log as a separate file, see #1978 . The strange thing is that when I intentionally triggered it via `killall -SEGV dosemu.bin` the log also appears where we would normally expect it too. See this run https://github.com/andrewbird/dosemu2/actions/runs/4564121797/jobs/8053488144 .

**Pull request merged**
