### PR TITLE
CI: Add freecom build test

### PR DESCRIPTION
**Pull request by andrewbird**
Started to add FreeCOM build test. Sorry I couldn't find the ticket where you requested this to reply there? Anyway there seem to be several problems.

#### FreeCOM
~Strings tool seems to be being built in wrong memory model~

#### Dosemu
MS-DOS 6.22 hasn't got enough environment space
~FDPP gets further but fails trying to locate watcom header files~
~FreeDOS 1.3 gets the furthest and builds lots, but is missing the string tool from above so ultimately fails.~

- [x] I think I have to fix the FreeCOM strings problem and get a clean build there first.
- [x] stsp debugged wmake / comcom interaction and recommended a workaround

### CODE REVIEW

**Comment by stsp** [comment]
> Sorry I couldn't find the ticket where you requested this to reply there?

https://github.com/dosemu2/comcom64/discussions/91

**Comment by stsp** [comment]
> MS-DOS 6.22 hasn't got enough environment space

It can be extended in config.sys:
https://github.com/dosemu2/dosemu2/blob/devel/src/bindist/c/config.sys#L18
Replace `1024` with something else.

**Comment by stsp** [comment]
> Strings tool seems to be being built in wrong memory model

How is so?
Is it even related to dosemu?

**Comment by stsp** [comment]
> Replace 1024 with something else.

And if that helps, please do so in
all config.sys files and submit a PR? :)

**Comment by andrewbird** [comment]
The strings tool is required for the build for i18n, so it's a problem i need to fix for the build to continue.

**Comment by stsp** [comment]
But how building for the wrong
memory model is related to dosemu?
Some comcom bug? Or what?

**Comment by j2969719** [comment]
>Strings tool seems to be being built in wrong memory model

I looked in the diff and saw that at some point I seemed to just silenced this ifdef...

el_risitas.pcx

**Comment by andrewbird** [comment]
I'm not saying the strings failure is due to dosemu, only that it's preventing getting to the build stage where the OP reported the problem with library.

**Comment by stsp** [comment]
Ah but you like fixing freedos, I know
that already from a few git logs. :)

**Comment by andrewbird** [comment]
The strings tool build problem is now fixed (there was a PR already waiting to be applied for this) and so the test now passes on FreeDOS 1.3.
I'm still having trouble with the build on MS-DOS 6.22. I tried increasing the env size all the way up to 4096, but I still see out of env space messages.

**Comment by stsp** [comment]
If you believe this is dosemu bug,
then please submit the report. Or PR. :)

**Comment by stsp** [comment]
So what's the status of this?

**Comment by andrewbird** [comment]
Passes on FreeDOS 1.3, OpenDOS 7.01 and FDPP, but currently I have MS-DOS 6.22 marked as a known failure.

**Comment by stsp** [comment]
Ok.

**Comment by stsp** [comment]
You can get it to work on ms-dos 6.22
by adding this to dosemu2 command line:
`COMSPEC=E:\command.com`.
The problem is described here:
https://www.sosoft.com/fod/fod_986.htm
but I wasn't able to apply their patch.

Essentially, DOSes prior to 7.0 make no
space reserve when copying env to child.
fdpp and freedos reserve 83 bytes, which
is sufficient for the build, but with comcom64
the problem doesn't exist at all, since it
keeps all its env in the DPMI memory space,
exporting only "PATH" to DOS (without
"PATH" WordPerfect fails, otherwise there
would be no envs visible to DOS at all).

**Pull request merged**
