### PR TITLE
Random issue with FDPP after installing emufs.com

### PR DESCRIPTION
**Pull request by andrewbird**
See discussion on #1126, will keep this PR open until we discover what the problem is with FDPP.

### CODE REVIEW

**Comment by stsp** [comment]
All checks have passed though?

**Comment by andrewbird** [comment]
I've restarted the test.

**Comment by andrewbird** [comment]
It passed again, I'll try it five times.

**Comment by andrewbird** [comment]
That one failed.

**Comment by andrewbird** [comment]
BTW, I seemed to be getting two builds of the PR, one from the free version of Travis, one from the pro version(one passed, one didn't). I disabled the pro one now by revoking its oauth token. Let's see if it makes any difference.

**Comment by andrewbird** [comment]
So crashed 2 out of 5 tests.

**Comment by stsp** [comment]
I added "Recommends: gdb" to get a better logs.
Could you please see if the logs are now better?

**Comment by andrewbird** [comment]
I added gdb to the .travis.yml as it doesn't follow the debian packaging rules.

**Comment by andrewbird** [comment]
the check is failing and has gdb info

**Comment by stsp** [comment]
Am I right that the same test always failing?
Test PP-DOS-GIT FAT FCB file rename source missing

**Comment by stsp** [comment]
Can we have also the DOS output
from -td mode? I am wondering at what
stage does it crash: boot or when running
test?

**Comment by andrewbird** [comment]
It's already there, named expect.log. You can see the crash occurs at the start of the command.com, but before processing anything in autoexec.bat.
~~~
- InitDisk: 

C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB

D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB

E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

                                                                               

                                                                               

dosemu XMS 3.0 & UMB support enabled

dosemu EMS driver rev 0.8 installed.

EMUFS host file and print access available

dosemu CDROM driver installed (V0.2)

Kernel: allocated 115 Diskbuffers = 62560 Bytes in HMA

emufs: redirector enabled

Process 0 starting: G:\command.com /e:384 /k %FDPP_AUTOEXEC%

ERROR: MCB corruption, good:02b8:0000 bad:9f84:0000

fdpp crashed.

ERROR: fdpp: abort at memmgr.cc:166

Press any key to exit.

~~~

**Comment by stsp** [comment]
So it doesn't seem to depend on a
test configuration, and should just
happen on normal start, if one wants
to reproduce it?

**Comment by stsp** [comment]
Could you try disabling emufs.com?

**Comment by andrewbird** [comment]
Sure, it's what I did in the previous PR to isolate the problem.

**Comment by stsp** [comment]
Ah, I thought it was emufs.sys previously, not com!
Sorry.

**Comment by andrewbird** [comment]
running now

**Comment by stsp** [comment]
Good that its com and not sys, as at least
its small.

**Comment by andrewbird** [comment]
I could temporarily disable the FreeDOS tests to speed things up too?

**Comment by stsp** [comment]
So am I right that emufs.com does not
break freedos and MS-DOS? Is it currently
used with them on travis?

**Comment by andrewbird** [comment]
Ignore this test, I made a mistake and disabled it in the generic config.sys, not fdppconf.sys!

**Comment by stsp** [comment]
It doesn't matter.
How is it currently on devel?
Where is emufs.com endabled, and where not?

**Comment by andrewbird** [comment]
it is used in this PR and doesn't break freedos. it's not enabled for MS-DOS in this PR and also currently isn't tested.

**Comment by andrewbird** [comment]
devel is fine, but emufs.com isn't used for any DOS at the moment

**Comment by stsp** [comment]
Could you please add another PR that
uses the default config for freedos, and
adds emufs.com for the config of msdos?
If it works fine, we can merge at least that.

**Comment by andrewbird** [comment]
okay will do

**Comment by andrewbird** [comment]
Are you happy to enable the tests for MS-DOS 6.22, obviously it will increase the test time by 50%?

**Comment by andrewbird** [comment]
I meant in the other PR that 'uses the default config for freedos, and
adds emufs.com for the config of msdos?'

Anyway I pushed the branch with it, let's see what happens in the test.

**Comment by stsp** [comment]
Yes, as I intend to merge it if it works.
no need to disable the MS-DOS tests
there. I think /F will already give a good
speed-up.

**Comment by stsp** [comment]
Maybe the same revert will help here?
I just wonder if maybe no KVM on travis?

**Comment by andrewbird** [comment]
kvm cputest works on travis fine.

**Comment by stsp** [comment]
Could you please rebase and give a
status update? We now have all DOSes
but fdpp running with emufs.com, and
that works fine, right?
Also all DOSes run with /F right?

**Comment by andrewbird** [comment]
I've rebased this branch on devel now.

Current devel status is all DOSes running with `install=emufs.com`, except FDPP.
This branch changes FDPP to use the standard fdppconf.sys, hence has `install=emufs.com`. I expect it to fail sporadically.

Yes all DOSes have /F now.

**Comment by stsp** [comment]
As predicted... it failed.

**Comment by stsp** [comment]
I added valgrind and gdb to travis.
Could you please upload a patch
that will call "dosemu -valgrind" on
fdpp tests?

**Comment by andrewbird** [comment]
Is it okay if I just add the options `"-I", "cpu_vm emulated cpuemu vm86sim cpu_vm_dpmi kvm"`, as the dosemu script doesn't play nicely with the way I'm driving dosemu with python pexpect?

**Comment by andrewbird** [comment]
Sorry, I just had to dash out for a few minutes. I added just the cpu options above, and it still crashes. I'm now going to enable valgrind.

**Comment by andrewbird** [comment]
I just cancelled the tests and repushed without msdos and freedos, as it's very slow.

**Comment by stsp** [comment]
I thought you can have a different
startup options for different tests. ;)

**Comment by stsp** [comment]
Could you please add into fdpp builddir
the file named `local.mak` with the following
content:
```
DEBUG_MODE = 1
EXTRA_DEBUG = 1
USE_UBSAN = 1
```
We need a debug build anyway, so
this can be w/o valgrind (in separate
PR, so that we can apply and rebase).

**Comment by andrewbird** [comment]
Okay, will add local.mak

I'm struggling to see anything but the valgrind output, will investigate.

**Comment by andrewbird** [comment]
valgrind is stealing `dosemu -td` output, will try again later.

**Comment by stsp** [comment]
But if I do `dosemu -valgrind -td` locally,
it all works.

**Comment by andrewbird** [comment]
I think pexpect wants a Pty .

**Comment by andrewbird** [comment]
I've tried lots of things for pexpect to get the output from dosemu when running under valgrind, but to no avail. I think it might be possible if `dosemu -td` could read and write from a socket as pexpect can optionally use an open file descriptor instead of stdin/stdout, but I imagine that's quite a big job?

I saw some of the changes you've made to python tests, like using `-td` instead of `-I video{none}`, so I could roll them back in, but I don't want to make your testing more awkward.

I also saw you've found the fdpp mistake in `.travis.yml`, thanks!

**Comment by stsp** [comment]
> optionally use an open file descriptor instead of stdin/stdout, but I imagine that's quite a big job?

Why not create such redirect with socat?

**Comment by stsp** [comment]
I seem to have applied the preliminary
fix. This looks a freedos bug to me, but
the one that I made much worse during
conversion to fdpp.
So lets have a clean PR that only uses
default config for fdpp.

**Pull request closed without merging**
