### PR TITLE
clipboard: refactoring [#2088]

### PR DESCRIPTION
**Pull request by stsp**
Move non-native funcs to shared place and used them in a term plugin.

### CODE REVIEW

**Comment by ecm-pushbx** [comment]
I only tested on the server in `-tc` mode yet, will test SDL later. It appears writing and reading work, but writing always writes the terminal command data to the screen, and I think reading sometimes does that too. Other than that it works, so definitely heading the direction I wanted.

**Comment by ecm-pushbx** [comment]
Wait, reading doesn't seem to work all the time. Getting confused mix ups here. I will try to reproduce.

**Comment by ecm-pushbx** [comment]
Files in https://pushbx.org/ecm/test/20230912/

Expected output is

First `-p` command: Empty output.

Second: A 0, A 1

Third: A 0, A 1, A 0, A 1

Fourth: A 0, A 1, A 0, A 1, B 0, B 1

Fifth: B 0, B 1

Actual output is very different. See screenshots:

Screenshot_20230912-204806
Screenshot_20230912-204841

**Comment by ecm-pushbx** [comment]
The two screenshots are of different runs, in their own dosemu2 instance each. It seems the exact corrupted contents are reproducible as both screenshots look very similar. (But I didn't check whether they're all same.)

**Comment by ecm-pushbx** [comment]
Running same test again a few minutes later the corrupted output differs:

Screenshot_20230912-205603

**Comment by ecm-pushbx** [comment]
All tests done with `~/local.new/bin/dosemu -K "$PWD" -tc` and with `C:\bin\toclip.exe` as a symlink into my toclip repo.

**Comment by stsp** [comment]
Is it the same with sdl?

**Comment by ecm-pushbx** [comment]
> Is it the same with sdl?

I will test tomorrow.

**Comment by ecm-pushbx** [comment]
`toclip -e` (erase only) doesn't seem to have any effect.

**Comment by stsp** [comment]
I think the weird messages are
from the garbled terminal. They
likely do not exist actually.

**Comment by ecm-pushbx** [comment]
https://github.com/dosemu2/dosemu2/blob/c624faa2fa6e14a0a655bf136998d4591265fdcd/src/plugin/term/clip_term.c#L33 seems to never call `cnn_clear`

**Comment by stsp** [comment]
Thanks!
Excellent catch.

**Comment by ecm-pushbx** [comment]
That's that fixed. However, I would like a mode like SDL with its native clipboard disabled where you don't write the escape sequences.

**Comment by stsp** [comment]
OK, should now work that way.

**Comment by ecm-pushbx** [comment]
Didn't pull your latest revision yet, but found another bug. Writing my fdconfig.sys to the clipboard (>400 Bytes) then reading it back results in truncation to 256 Bytes. (I enabled an `#if 0` commented out debug dump in `toclip` to check what it is writing.)

Screenshot_20230912-213800

**Comment by ecm-pushbx** [comment]
Did you mean to drop the conditional here? Judging from the unindent.

```
CONSTRUCTOR(static void clipterm_initialize(void))
{
  if (config.clip_term
```

**Comment by stsp** [comment]
All fixed.

**Comment by ecm-pushbx** [comment]
Many thanks! Both tests run fine now, without `-tc`. With `-tc` there's the expected noise on the terminal.

**Comment by ecm-pushbx** [comment]
I will check SDL tomorrow as I mentioned.

**Comment by ecm-pushbx** [comment]
https://github.com/dosemu2/dosemu2/blob/b1de57e5f2da315b1a607867b6f2411a12ea005f/src/plugin/sdl/clip_SDL.c#L161

This message refers to GetSize but is actually in `sdlclip_paste`. (I did not try this PR with SDL yet.)

**Comment by stsp** [comment]
OK, fixed msg.

**Comment by ecm-pushbx** [comment]
Just tested, everything seems to work as expected with SDL and with `-t` mode or `-tc` mode. I had to disable Alt + Left Mouse Button moving a window in my window manager though, in order to use SDL mode's [Alt+Shift+Lmb to copy from DOS clipboard to host clipboard](https://github.com/dosemu2/dosemu2/wiki/Clipboard-usage). Described in a comment on https://askubuntu.com/questions/118151/how-do-i-disable-window-move-with-alt-left-mouse-button-in-gnome-shell/1000966#1000966 :

> This works for Mate 18.04 through Control Centre > Look and Feel > Windows > Behaviour > Movement Key

I do have one more wish though, if the clipboard is not supported (in `-X` mode) can you make it so the installation check fails rather than clearing or writing to the clipboard failing and reading always reading an empty clipboard?

**Pull request merged**
