### PR TITLE
First phase of asm removal in fp87-sim.c

### PR DESCRIPTION
**Pull request by bartoldeman**
Replaces ftest() by plain C, and removes some unnecessary FPU inits, applying to the real, not simulated FPU.

### CODE REVIEW

**Comment by bartoldeman** [comment]
Ref: #1833

**Comment by bartoldeman** [comment]
Note though that few other architectures have 80-bit long double FP, long double may be 128 or 64 bits.
So while this gets it compiled eventually there will be more roadblocks.

Bochs and QEMU use forked softfloat libraries to do all FP using integers (http://www.jhauser.us/arithmetic/SoftFloat.html), that would be the only way to do it 100% accurate.

AFAICS dosbox just uses 64bit doubles internally with a few adjustments to allow for memcpy using long doubles, and gets away with it.

**Comment by stsp** [comment]
You have a typo in log msg,
fp87-test.c is supposed to be
fp87-sim.c.

**Comment by stsp** [comment]
> AFAICS dosbox just uses 64bit doubles internally with a few adjustments to allow for memcpy
> using long doubles, and gets away with it.

Whatever looks simple.
If dosbox gets away with it, then I
suppose we can too? Also perhaps
thats faster than to use ints?

**Comment by bartoldeman** [comment]
yes best to keep it simple for now.

Sure native floats are very fast on modern CPUs (up to 32 double ops/cycle if you have avx512 and vectorize), but in the simulator there's tons of overhead anyway.

QEMU has shortcuts so e.g. doubles are done natively, for speed (but adds complexity).

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
