### PR TITLE
CI: Don't run scheduled jobs on forks

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
Why do we need this?
But ok.

**Comment by andrewbird** [comment]
Because otherwise everyone who forks dosemu2 runs those same scheduled tests.

**Comment by stsp** [comment]
Why do we care?
Have anyone complained?

**Comment by andrewbird** [comment]
Nobody complained, but seeing as Github give us free CI, I didn't want to abuse it. It'll surely make no difference unless everyone develops a conscience, but I'd like to think it'll make another Travis type situation less likely.

**Comment by stsp** [comment]
So is this just for an extra care, or
do you mean forks running CI would
drain the CI credits from us?

**Comment by andrewbird** [comment]
Just for extra care.

**Pull request merged**
