### PR TITLE
Travis ci 45

### PR DESCRIPTION
**Pull request by andrewbird**
A few updates here:
- The long overdue switch to testing on Focal
- A precursor to my being able to test any future DOS file attributes patch that needs xattrs, is the switch to support a test directory outside of the build
- New test for ECM's int21/7142 64 bit seek on MFS

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!

**Comment by stsp** [comment]
> The long overdue switch to testing on Focal

What about -m32 build?
Can we test it now?

**Comment by andrewbird** [comment]
> What about -m32 build?

Not sure what you mean, can you elaborate?

**Comment by stsp** [comment]
I am not sure we can now test `--with-target-bits-32`
as on focal multilib may not work.

**Pull request merged**
