### PR TITLE
CI: Update to use FreeDOS 1.3 [skip ci]

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
How come it is skip ci?

**Comment by stsp** [comment]
1.2 is excluded from any
auto testings, right?

**Comment by andrewbird** [comment]
Skip ci because freedos is only triggered on the weekly Cron job, so no point.

**Comment by stsp** [comment]
How about `[full ci]` then?

**Comment by andrewbird** [comment]
Sure, I forgot about that.

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
