### PR TITLE
Introduce dosrc.d, but comcom32 doesn't do for loops yet

### PR DESCRIPTION
**Pull request by jschwartzenberg**
This contains the line to introduce `dosrc.d`. Without a for loop for now due to limitations in comcom32.

### CODE REVIEW

**Comment by stsp** [comment]
Must be before userhook.

**Comment by jschwartzenberg** [comment]
But then the message might not be visible anymore if the userhook prints a lot. Now it will always be at the end.

**Comment by stsp** [comment]
userhook may not return.
It is for running Norton Commander/dos navigator.

**Comment by jschwartzenberg** [comment]
Fixed!

**Comment by jschwartzenberg** [comment]
Makes a lot of sense to run Norton Commander indeed, that was a common setup back in the day!

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
