### PR TITLE
simx86: never unprotect VGA memory

### PR DESCRIPTION
**Pull request by stsp**
Integrating faultless VGA with simx86 is
very difficult. I decided to split the work to
smaller pieces, for an easier review by
others.

### CODE REVIEW

**Comment by stsp** [comment]
Thanks, fixed comment and applied.
I forgot that in vgacpy branch it doesn't
change the protection.
I also uploaded the mapbase branch,
where I tried to add the separate cpuemu
mem base. I actually got SIM to work,
but jit is still unreliable. :(
Initially I didn't want to alias DPMI, but
it turned out you can't make jit to work
with the split layouts.
When this works, my plan is to keep
vga memory protected only on the emu
alias, and never unprotect it there.
That way I'll get the fault-less VGA
for native modes (with memcmp), and
mostly faultless in jit mode (and no
memcmp there).

**Comment by stsp** [comment]
Any help or comments are appreciated.
Hell knows why jit sometimes gives a
page fault exception to DPMI (vm86jit
seems to work).

**Comment by bartoldeman** [comment]
For VGA memory there is also vga.mem.base, which is unprotected for both LFB & normal mem.
Then instead of `WRITE_BYTE()`, `vga_write()` could write directly to the correct place in `vga.mem.base`, and then set that page dirty (which it already does in vga.instemu mode after all but with more complex logic).

As for the memcmp part, I am still not sure if it improves things, would need to test it a little -- you're burning more CPU if a large VGA buffer of say 1024x768 in true color does not change, even if a memcmp of 4096 bytes can be faster by itself than a page fault.

**Comment by stsp** [comment]
I do not seek for an unprotected media.
The problem is deeper.
When you have native dpmi and vm86jit,
you have no other choice but to alias
everything. :(

Yes, cpu burning is bad, but you burn
another core. DOS prog then executes
in a faultless manner, so it is much
faster. But lets think about compromises.
At least I should not remove the fault
code right away.

**Comment by stsp** [comment]
Lets assume I only want to never
unprotect in jit mode, and do not
want any change for native mode
(leave it faulting). Even in that case
I already have to alias everything! :(
Unless we disallow native dpmi+vm86jit.
So I really see no way around that.

**Comment by stsp** [comment]
I looked into a jit code and found
that supporting a fancy layouts
(separate mem bases for vm86 and
dpmi) is not an option. Or do you
know how to do that w/o adding
conditional jumps to every address
gen? IMHO aliasing everything is
not that bad. I think that even shared
mem is not committed unless touched,
and we initially set all mappings to
PROT_NONE and commit on demand.
I think linux can and will do all the
needed optimizations.

**Comment by stsp** [comment]
Also think about dpmi jit + vm86kvm.
It will work. And this is a really needed
combination.
So I think aliasing everything is a
long lasted due.

**Comment by stsp** [comment]
I fixed a silly bug, and now jit mostly work...
But not quite. :)
With this change:
```
diff --git a/src/base/emu-i386/simx86/trees.c b/src/base/emu-i386/simx86/trees.c
index 6e492528e..e81e10023 100644
--- a/src/base/emu-i386/simx86/trees.c
+++ b/src/base/emu-i386/simx86/trees.c
@@ -961,10 +961,10 @@ TNode *Move2Tree(void)
 /**/ if (nG==NULL) leavedos_main(0x8201);
 
   if (found) {
-       if (debug_level('e')>2) {
-               e_printf("Equal keys: replace node %p at %08x\n",
+//     if (debug_level('e')>2) {
+               error("Equal keys: replace node %p at %08x\n",
                        nG,key);
-       }
+//     }
        /* ->REPLACE the code of the node found with the latest
           compiled version */
        NodeUnlinker(nG);
```

I can see lots of "Equal keys" msg even
on devel. So this is likely not the source of
my problems, but any idea where do the
equal keys come from? Is it normal? I
thought the mpmap logic should prevent
that, what am I missing?

**Comment by bartoldeman** [comment]
I'll have a look at the "equal keys" issue later; I have now created a PR in #1107 to never unprotect VGA memory in both JIT and sim. That's not the most efficient implementation but minimal (in order to help bisects should they be necessary).

**Comment by stsp** [comment]
I already found the reason for equal keys:
this is because the inodes are not removed
by invalidation. They are only unlinked and
left dangling for a later GC.
Note that forcibly removing them on invalidation
actually 90% fixes the #86. But I don't know
yet why, and I don't know where other 10%
are. :)

**Pull request closed without merging**
