### PR TITLE
CI: Add manual trigger for ASAN [skip ci]

### PR DESCRIPTION
**Pull request by andrewbird**
Merge this to devel, then navigate to 'Actions' tab, click on 'Manual (ASAN)' in left pane, then do 'run workflow'

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
How about other triggers
for completeness?

**Comment by andrewbird** [comment]
Will add 'full' as soon as you test this to your satisfaction

**Comment by stsp** [comment]
In a mean time I removed the
white-space errors from that
file. You might be using some
bad editor.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/actions/runs/3267858186
Testing.
But no matter whether it fails
or not, I am definitely satisfied
with it being there. :)

**Comment by andrewbird** [comment]
Sorry about the whitespace, I pasted the code from another terminal and missed it during cleanup.

**Pull request merged**
