### PR TITLE
simx86: handle mov ss/pop ss correctly for compiled code (see #1147)

### PR DESCRIPTION
**Pull request by bartoldeman**
CeS_LOCK was only set in the interpreter and not set correctly when executing
JITted code. To handle this introduce new TNode flags F_INHI/M_INHI
(INHI=Inhibit Interrupts) and also rename CeS_LOCK to CeS_INHI to remove
confusion with the LOCK instruction.

The tests in src/tests test this in protected mode where it still goes via
the interpreter. I tested it in vm86 mode too in DEBUG single stepping through
pop ss and seeing that that would skip the instruction after pop ss.

### CODE REVIEW

**Comment by bartoldeman** [comment]
Yes I know you think it's still a fragile approach but it's the best I could come up with to fix the actual issue.

**Comment by stsp** [comment]
But what is the problem with doing
at the end of the interp loop code:
```
if ((TheCPU.mode & M_INHI) && PC != P0) {
  CODE_FLUSH();
  TheCPU.mode &= ~M_INHI;
}
```

instead of everything else you do in
the patch? What am I missing?

**Comment by stsp** [comment]
You can also check the `if (G->flags & F_INHI)` in
linker, and do not link such nodes. Then you don't
even need to interpret them. Or?

**Comment by bartoldeman** [comment]
The linker will not link such nodes now as it only links nodes that end with jump or call instructions (see here: https://github.com/dosemu2/dosemu2/pull/1209#issuecomment-645377763), and these nodes end with pop ss or mov ss.

(It should link such nodes though but that's for another day.. and then the check as you propose is needed -- or you can link, which then allows you to reset the flag as at least one instruction then follows it but then when breaking the link it needs be set again... that's probably too much bookkeeping).

The interpreter is used for pop ss and mov ss in protected mode. Since setting segments in protected mode is much more complex than in real/vm86 mode. It could be compiled but then should go via a helper function that is called from the JITted code.

**Comment by stsp** [comment]
OK, but what I don't understand is why
do you need multiple variables. You set
TheCPU.mode in interp, and CEmuStat
in executor, for the seemingly similar case.
IMHO you only need:
- make sure that pop ss forms a complete
node - can be done by CODE_FLUSH()
at the ent of interp loop.
- Set CEmuStat bit, either in interp or in
executor.
- make sure the next instr also forms a
complete not (another CODE_FLUSH())
- clear CEmuStat bit
- Check that aforementioned bit to suppress
TF traps and interrupt exits

In your patch you use 2 bits instead of
one, and one of them is still cleared in
HandleEmuSignals(). I am just trying
to understand what makes things that
complex, I am probably missing something.

**Comment by stsp** [comment]
I created the branch "lock" just to
show what exactly did I mean.
What do you think?

**Comment by stsp** [comment]
My branch even passes test. :)
So its probably correct.

**Comment by bartoldeman** [comment]
It's correct but it makes things less efficient. The issue is here with longer sequences, usually what we have is things such as (in Intel syntax)
```
mov ss,ax
mov sp,200
```
now without the trap flag you inserted an artificial break in the node.

Whereas in my patch while compiling (with the rebased forced update) it sets F_INHI when compiling mov ss,ax and then resets it when it sees another instruction follows it. So the end result is a sequence without F_INHI set and CEmuStat never gets CeS_INHI set either. Only if the very last instruction in the sequence modifies ss the sequence gets F_INHI (compile-time) and codegen-x86 will set CeS_INHI (run-time).

**Comment by stsp** [comment]
Yes, your current patch looks perfectly
fine. But we can still apply the small
modification after it, see my new patch
in the branch "lock".
Basically just to spare EmuHandleSignals()
from that stuff.

**Comment by stsp** [comment]
Thanks!

**Comment by bartoldeman** [comment]
I am not 100% sure about your lock branch, as I think the current handling is correct: if we have pop ss/mov ss, then *all* interrupts are blocked for one instruction (as if the two instructions are glued together) so CEmuStat is really a check-and-reset -- you don't want to trigger, say `int 8` (via `SIGARLM` and `CeS_SIGPEND`) in between `mov ss` and `mov sp`. And in your branch I don't see CEmuStat is cleared nor checked any more after FindExecCode.

**Comment by stsp** [comment]
One thing I dont like in current code,
is that it is handled by HandleEmuSignals().
If it is called more than once, it may cleat
lock and raise trap, because it doesnt
check ip. And you need to be careful to
prevent it from being called more than
once, because any return from an interp
loop will result in an extra call, and
forbidding all returns is quite bad.
Another problem is that it should only
guard 2 instructions but not more. Eg in
pop ss
pop ss
pop bp
the trap should happen after second pop ss,
not after pop bp, as only 1 inst maximum is
guarded. Same with
sti
pop ss
pop bp
Here, I believe, interrupts can trigger
after pop ss, but trap - only after pop bp.

**Comment by ecm-pushbx** [comment]
I think `sti` \ `pop ss` \ any other instruction should inhibit interrupts between the `pop`/`mov` to ss and the third instruction.

**Comment by stsp** [comment]
No because STI also inhibits interrupts
for 1 following instruction, and inhibitions
do not glue. I.e. they do not cover more than
2 instructions, ever. If you do "pop ss" 10
times in a row, only first 2 are "glued", then
the lock is dropped, AFAIK.

**Comment by bartoldeman** [comment]
You are right, hardware interrupts are only inhibited for one instruction following sti or pop/mov ss. So that needs an extra variable, a flag or the PC (as you do), so that the second pop ss in a row does not set the inhibition.

For compiled code it's not quite right yet either: if the executed sequence ends in pop ss and it finds code it should go straight back into the execution instead of going to the interpreter loop. Perhaps it's best if FindExecCode doesn't even look at CEmuStat but instead uses signal_pending() and G->flags -- that way codegen-x86.c doesn't need to set flags in CEmuStat any more either (in that case we need to carefully look at CODE_FLUSH too though when TF is set).

For the trap flag I need to do a few experiments to see how long it is inhibited, it's still not entirely clear to me.

**Comment by stsp** [comment]
I _suspect_ that TF inhibition also doesn't
glue, but is separate from the IF inhibition.
Would be cool if you verify that, thanks!

**Comment by bartoldeman** [comment]
Indeed TF inhibition doesn't glue, it also says so in the SDM:
https://software.intel.com/content/dam/develop/public/us/en/documents/253668-sdm-vol-3a.pdf
(section 6.8.3: "If a sequence of consecutive instructions each loads the SS register (using MOV or POP), only the first is guaranteed to inhibit or suppress events in this way")

now for:
```
sti
pop ss
pop bp
```
if TF is not set, hardware interrupts can happen after pop ss.
if TF is set, a trap happens after sti, where the trap handler (int 1) invalidates the inhibition. Then `pop ss` starts a new independent inhibition.

**Comment by stsp** [comment]
Cool, thanks!
Haven't thought that int1 just
invalidates an inhibition, but its
obvious when you know the answer.
Btw, I don't think we need the
very precise emulation of this
all. AFAIK even in v86 you don't
have such (and as the result, in
kvm/vm86).
But saving PC and moving things
out of EmuHandleSignals() at least
makes things much cleaner, so
indeed I'd like to see at least that
part in.

**Pull request merged**
