### PR TITLE
Xms fixes

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/actions/runs/12231233445/job/34113891016?pr=2320
```
 Traceback (most recent call last):
  File "/home/runner/work/dosemu2/dosemu2/test/func_cpu_methods.py", line 93, in do_test
    _dotest(self, *test)
  File "/home/runner/work/dosemu2/dosemu2/test/func_cpu_methods.py", line 68, in _dotest
    diff = unified_diff(refoutput, dosoutput, fromfile=reffile.name, tofile=dosfile.name)
           ^^^^^^^^^^^^
NameError: name 'unified_diff' is not defined
```

What's an error is this?
Andrew?

**Comment by stsp** [comment]
I probably fixed it myself now.
But is there any way to catch the
alike python failures beforehand?

**Comment by andrewbird** [comment]
> But is there any way to catch the
alike python failures beforehand?

Yes there is and I forgot to do it.
~~~
$ pyflakes3 test/func_cpu_methods.py 
test/func_cpu_methods.py:68:16: undefined name 'unified_diff'
~~~

Thanks for the fix!

**Comment by stsp** [comment]
And then people are wondering
why their github CI was attacked:
https://www.opennet.ru/opennews/art.shtml?num=62365
:)

**Pull request merged**
