### PR TITLE
simx86: generate code for RETisp (0xc2, ret near imm16)

### PR DESCRIPTION
**Pull request by bartoldeman**
Follow-up to #1116

### CODE REVIEW

**Comment by stsp** [comment]
Thanks!
Making all jumps compilable is actually
the great idea!

**Comment by stsp** [comment]
Well, on zx_emul this (or prev patches)
is almost a 2 times speed increase!
Absolutely fantastic!

**Comment by stsp** [comment]
Are you planning to do something about
your findings wrt -O0?

**Comment by bartoldeman** [comment]
#1114 is a start since debug_level is quite time-consuming (but by now it's unmergeable).
Many of the other functions are called far less often now.

If you want me to limit #1114, for the JIT most uses come from `Exec_x86()` and `_nodelinker2()`.

With #1118 and running zx_emul until the first text completes my top 10 is as follows now (in devel mode):
```
    17.02%  dosemu.bin      dosemu.bin              [.] debug_level
    13.01%  dosemu.bin      dosemu.bin              [.] FindTree
    10.86%  dosemu.bin      dosemu.bin              [.] Exec_x86
     8.73%  dosemu.bin      dosemu.bin              [.] _nodelinker2
     5.11%  dosemu.bin      dosemu.bin              [.] dosaddr_to_unixaddr
     3.27%  dosemu.bin      dosemu.bin              [.] FindExecCode
     2.45%  dosemu.bin      dosemu.bin              [.] mem_likely_protected
     1.47%  dosemu.bin      dosemu.bin              [.] do_read_byte
     1.26%  dosemu.bin      dosemu.bin              [.] NodeLinker
     1.26%  dosemu.bin      dosemu.bin              [.] e_querymark
```
In particular compared to https://github.com/dosemu2/dosemu2/pull/1092#issuecomment-611847047 `_Interp86()` went all the way down from ~5% to 0.27%.

`perf report` is really quite nice, with a text mode CLUI that allows you to go down to the asm level to see where most time is spent.
In particular with `-g` so I get the call graph. I think I'll see bye to good old `gprof`.

**Comment by stsp** [comment]
Yes, perf is definitely interesting!
I wasn't able to get anything useful
from gprof, and even supporting it
in dosemu2 was not easy. :)

**Pull request merged**
