### PR TITLE
Dpmi1

### PR DESCRIPTION
**Pull request by stsp**
DPMI-1.0 support.

### CODE REVIEW

**Comment by stsp** [comment]
Hi Andrew, I think comcom32
changes now fail here, although
I can't reproduce locally.
Can you take a look?

**Comment by andrewbird** [comment]
mkdir seems to have trouble when creating new directory on non default drive
~~~
Welcome to dosemu2!
    Build 2.0pre9
C:\>mkdir c:\tmp
C:\>dir
 Volume in drive c is /home/ajb/dosemu/drive_c
 Directory of c:\
 
2023-08-30 18:35 <DIR>         tmp
         0 file(s)              0 bytes
         1 dir(s)            36.7 GB free
C:\>d:
D:\>mkdir c:\tmp2
Could not create directory - c:\tmp2
D:\>
~~~

**Comment by andrewbird** [comment]
actually the directory was created, so perhaps only the return value is wrong.

~~~
D:\>dir c:
 Volume in drive c is /home/ajb/dosemu/drive_c
 Directory of c:\
 
2023-08-30 18:36 <DIR>         tmp2
2023-08-30 18:35 <DIR>         tmp
         0 file(s)              0 bytes
         2 dir(s)            36.7 GB free
~~~

**Comment by stsp** [comment]
```
C:\>d:
D:\>mkdir c:\tmp2
D:\>cd c:\tmp2
C:\tmp2>ver /r
comcom32 v0.2
 Source Control Revision ID: alpha-3-74-g13b013d
```

Maybe you already had c:\tmp2?

**Comment by andrewbird** [comment]
No it was a clean ~/.dosemu. I also tried with LFN which seems to work, but again wrong result
~~~
D:\>mkdir c:\verylongdir
Could not create directory - c:\verylongdir
D:\>dir c:
 Volume in drive c is /home/ajb/dosemu/drive_c
 Directory of c:\
 
2023-08-30 18:36 <DIR>         tmp2
2023-08-30 18:42 <DIR>         verylongdir
2023-08-30 18:35 <DIR>         tmp
         0 file(s)              0 bytes
         3 dir(s)            36.7 GB free
~~~

**Comment by andrewbird** [comment]
My comcom32 is from PPA
~~~
D:\>ver /r
comcom32 v0.2
 
Reported DOS version (Int21.3000): 5.00 OEM: FDh
Reported true DOS version (Int21.3306): 7.10
Version string (Int21.33FF): FDPP kernel 1.6 [GIT: ] (compiled Aug 23 2023)
~~~

Not sure how to explain that yours works and mine(PPA) doesn't

**Comment by stsp** [comment]
Maybe PPA didn't update yet?

**Comment by stsp** [comment]
It did...

**Comment by stsp** [comment]
Could you please bisect comcom32?
There were just a couple of patches,
I guess that's because of LFNs, but
who knows.

**Comment by andrewbird** [comment]
I will try later.

**Comment by stsp** [comment]
So if directory was created, then
djgpp does some chmod magic on
it:
```
  /* mkdir is stub'd, and we don't want to stub chmod also.  */
  attr = _chmod(dir_name, 0, 0);

  /* Must clear the directory and volume bits, otherwise 214301 fails.
     Unused bits left alone (some network redirectors use them).  Only
     care about read-only attribute.  */
  if (_chmod(dir_name, 1, (attr & 0xffe6) | ((mode & S_IWUSR) == 0)) == -1)
    return -1;
  return 0;
}
```

This is the only code that is
executed when dir already created.

**Comment by stsp** [comment]
Still can't reproduce, but chmod was
quite a clue. Seems there are many
bugs on that front, lets see.

**Comment by stsp** [comment]
What umask do you have?

**Comment by stsp** [comment]
So found 2 bugs in dosemu2 and
2 in comcom32 in the dir creation
code. Amazing. :)

**Pull request merged**
