### PR TITLE
Coverity: Target and source overlap for assignment

### PR DESCRIPTION
**Pull request by andrewbird**
Problematic patch which seems to break cpu tests...

### CODE REVIEW

**Comment by andrewbird** [comment]
And yet on its own it passes!

**Comment by andrewbird** [comment]
This the previous test of this patch(and others) that failed https://travis-ci.com/github/dosemu2/dosemu2/builds/186759106

**Comment by stsp** [comment]
JIT DPMI fails randomly, disregard it.

**Comment by andrewbird** [comment]
Okay, thanks, I'll close this and add the commit back into coverity-03 (along with the other changes you asked for)

**Pull request closed without merging**
