### PR TITLE
Test

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by andrewbird** [comment]
Does the 64 bit host executable link for you? I see
~~~
gcc -m64 -Wall -O2 -g -fno-strict-aliasing -fno-pic -fno-pie  -o native64 ./test-i386.c -lm
./test-i386.c:2418:1: warning: specifying vector types with __attribute__ ((mode)) is deprecated [-Wattributes]
 2418 | typedef int __m64 __attribute__ ((__mode__ (__V2SI__)));
      | ^~~~~~~
./test-i386.c:2418:1: warning: use __attribute__ ((vector_size)) instead [-Wattributes]
./test-i386.c:2419:1: warning: specifying vector types with __attribute__ ((mode)) is deprecated [-Wattributes]
 2419 | typedef float __m128 __attribute__ ((__mode__(__V4SF__)));
      | ^~~~~~~
./test-i386.c:2419:1: warning: use __attribute__ ((vector_size)) instead [-Wattributes]
/usr/bin/ld: /tmp/ccy5vfoI.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: native64] Error 1
~~~

**Comment by stsp** [comment]
Yes, I can reproduce the problem on
ubuntu, but on fedora it works OK...

**Comment by stsp** [comment]
But its not a regression of this patch.

**Comment by andrewbird** [comment]
Sorry, no, I should have said so. But I wonder if it's working for you?

**Comment by andrewbird** [comment]
I see you already answered that!

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Thanks, it links and runs now.

**Pull request merged**
