### PR TITLE
Lpage

### PR DESCRIPTION
**Pull request by stsp**
Hi @andrewbird could you please
try this?

### CODE REVIEW

**Comment by andrewbird** [comment]
Sorry, still not quite right. 
[t14.zip](https://github.com/user-attachments/files/18085647/t14.zip)

**Comment by stsp** [comment]
Would it be possible to arrange an
ssh to this box?

**Comment by andrewbird** [comment]
The box contains no sensitive data so that's good, but I have an ISP supplied proprietary router that doesn't offer any interface to allow such access. Sorry!

**Comment by stsp** [comment]
ssh supports reverse tunneling.
In this case you connect to my pc,
which opens a new port on my pc
to which I can connect to yours.
Or something like that. :)

**Comment by andrewbird** [comment]
Okay I'll investigate that tomorrow.

**Comment by andrewbird** [comment]
So I think I understand what to do with this reverse ssh thingy. As I understand it i'd need connection details for yourself. Do you want to send them to ajb@spheresystems.co.uk?

**Comment by stsp** [comment]
Sent.

**Comment by andrewbird** [comment]
I don't know if it helps, but as you saw from my log earlier, dosemu fails  with `-S`, `-X`, and  `-t`, but as you saw is okay with `-td`. The surprise to me is the `-t` failure, what subsystem is shared by those three but not the `-td`?

**Comment by stsp** [comment]
```
  /* init vgaemu & render before initing video subsystem */
  if (!config.vga) {
    vga_emu_pre_init();
    if (!config.dumb_video)
      render_init();
  }
```

vgaemu is used even in terminal
mode too, because text mode also needs
emulation. But dumb mode only supports
tty output on int10 level.

**Pull request merged**
