### PR TITLE
Patch for Seven Cities of Gold [#1678]

### PR DESCRIPTION
**Pull request by jschwartzenberg**
Here's the commit with the updated sgml. I couldn't quickly figure out how to regenerate the html. Could you give me a hint so I can amend the commit?

### CODE REVIEW

**Comment by stsp** [comment]
Why sgml?
You could alter wiki.
Lets remove sgml.

**Comment by jschwartzenberg** [comment]
Should I create a PR to remove it all. The wiki now says it was generated from the repo. Would I remove just the tweaks or everything?

**Comment by stsp** [comment]
No rush to remove, have you
updated the wiki?

**Comment by stsp** [comment]
Lets apply if you already wrote
the patch.

**Comment by jschwartzenberg** [comment]
Added to the wiki as well now.

**Pull request merged**
