### PR TITLE
Umip

### PR DESCRIPTION
**Pull request by stsp**

### CODE REVIEW

**Comment by ecm-pushbx** [comment]
Is it still valid to run `smsw` in Virtual 86 Mode if this is merged?

**Comment by stsp** [comment]
As you can see from the patch,
if the destination is register, then
0x31 is written there. If destination
is memory, the instruction is just
skipped.
Of course you are welcome to
provide the modrm decoder. :)

**Comment by stsp** [comment]
Also this is another example where the
native dpmi fails but kvm works, as
unfortunately they decided to circumvent
UMIP in the kernel.

**Comment by ecm-pushbx** [comment]
I only use `smsw ax` so this is fine.

**Comment by stsp** [comment]
Hi Bart, would you like to review
this? In particular the instremu change
where I added the UMIP instructions
to instr_len(). I did that rather blindly
so would be good to know what you
think.

**Pull request merged**
