### PR TITLE
simx86: use read/write functions for FPU sim code

### PR DESCRIPTION
**Pull request by bartoldeman**

### CODE REVIEW

**Comment by bartoldeman** [comment]
hmm it seems Travis is not running under the organization yet!

**Comment by bartoldeman** [comment]
@stsp I think you need to grant access to the dosemu2 organization on the travis-ci.com login screen.

**Comment by stsp** [comment]
The procedure was a bit longer.
Had to add that organization to my
account on travis, then install the
travis application into an organization,
and remove the access restrictions
from it.

**Comment by stsp** [comment]
Thanks!

**Pull request merged**
