### PR TITLE
CI: Don't cancel the other runs after 1st failure [skip ci]

### PR DESCRIPTION
**Pull request by andrewbird**

### CODE REVIEW

**Comment by stsp** [comment]
Thanks.

**Comment by stsp** [comment]
How about [scheduled ci] instead of
[skip ci] in this patch?
How to run this manually now?

**Comment by andrewbird** [comment]
`[skip ci]` only affects the Triggered runs, having it has no effect on Scheduled or Manual initiated runs.

**Comment by stsp** [comment]
I meant, we had to trigger the
scheduled CI on that commit to
test the packages again.
I don't know how to do that manually.
Although that wasn't going to
help because of the XMS regression
that is now fixed.

**Comment by andrewbird** [comment]
> I don't know how to do that manually.

This might work, but I don't have time to test it at the moment.
```diff
ajb@calypso:/clients/common/dosemu2.git$ git diff
diff --git a/.github/workflows/ci-scheduled.yml b/.github/workflows/ci-scheduled.yml
index 1877d954d..24770e1dc 100644
--- a/.github/workflows/ci-scheduled.yml
+++ b/.github/workflows/ci-scheduled.yml
@@ -3,6 +3,7 @@ name: Scheduled
 on:
   schedule:
     - cron: '23 23 * * 0' # 23:23 Every Sunday
+  workflow_dispatch:
 
 jobs:
   asan:
```

**Comment by stsp** [comment]
What does this mean and how to
use it?

**Comment by andrewbird** [comment]
Sorry, if you commit this to devel (with skip ci) then you should be able to navigate to https://github.com/dosemu2/dosemu2/actions/workflows/ci-scheduled.yml and trigger manually. I'm a bit vague here as I don't have permission myself to manually trigger a run, so I don't see the same UI as you will here.

**Comment by stsp** [comment]
image
It doesn't look like there is some
"trigger" button, and "New workflow"
button just leads to the workflow
marketplace.

**Comment by stsp** [comment]
Mmm, that worked!
Thanks. :)

**Comment by andrewbird** [comment]
Funny, I looked for your manual run of the scheduled action, but can't see it. I also checked https://github.com/stsp/dosemu2/actions but I get redirected to the dosemu2 page. Did it produce a clean run, and if not were all the various ubuntu packaged versions completed?

**Comment by stsp** [comment]
I didn't run it. :)
Just have a new button now, so
the patch worked.

**Comment by andrewbird** [comment]
Scheduled run seems to be failing on 20.04, 22.04, 24.04 and queued indefinitely on 24.10, see https://github.com/dosemu2/dosemu2/actions/workflows/ci-scheduled.yml

**Comment by stsp** [comment]
And why I haven't had any emails of that? :(

**Comment by stsp** [comment]
Do you have some ubuntu around?
I have just installed the packages on 24.10
and they seem to work fine.

**Comment by andrewbird** [comment]
> And why I haven't had any emails of that? :(

Because the job isn't complete (waiting for 24.10). 

> Do you have some ubuntu around?

Yes 24.04 but I have to go out now.

**Comment by stsp** [comment]
Ok, CI isn't helping us to ever
get the working packages. :)
Something must be done about
this.

**Pull request merged**
